- .travis.yml
Currently these latest versions are `4.4.7` for the 4.x branch and `6.2.2` for the 6.x branch
> Travis CI: Test on latest Node.js v4.x.x and v6.x.x branches

- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/requireParam.js
- tests/rules/assertions/requireParam.js
This fixes Issue #20.
See http://usejsdoc.org/tags-inheritdoc.html for the inheritdoc spec.
> Support @inheritdoc in the require-param rule

- .README/README.md
- .README/rules/require-example.md
- src/index.js
- src/rules/requireExample.js
- test/rules/assertions/requireExample.js
- test/rules/index.js
> Added rule: require-example

- package.json
- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
Simple regex check fails on non-ASCII descriptions.
> Correct check for non-ASCII descriptions

- README.md
- src/jsdocUtils.js
- test/rules/assertions/checkParamNames.js
This fixes the 'Unsupported function signature format.' error as per https://github.com/gajus/eslint-plugin-jsdoc/issues/18.
I cannot say that the testing for this has been rigorous, but it does seem to work for all basic cases. Then again, the fix is really simple and should always work, unless I'm missing something.
> Fix the 'Unsupported function signature format.' error.

- src/iterateJsdoc.js
Package `comment-parser` used to parse comments and extract description and tags expects comment blocks to be aligned and correctly indented as per JSDoc docs.
As an example it does not handle incorrectly aligned JSDoc blocks:
```
/**
* Add two numbers.
* @param {number} a
* @param {number} b
* @returns {number}
*/
function add(a, b) {
return a + b;
}
```
or
```
/**
* Add two numbers.
* @param {number} a
* @param {number} b
* @returns {number}
*/
function add(a, b) {
return a + b;
}
```
> fix: Preserve JSDoc block start/end indentation (#41)

- .README/README.md
- .README/rules/require-param-name.md
- README.md
- src/index.js
- src/rules/requireParamName.js
- test/rules/assertions/requireParamName.js
- test/rules/index.js
Hello, @gajus,
My team uses [Ramda](http://ramdajs.com), as a functional library. Unfortunately, we forget to write the Identifier's of the @param tag, because the code is the following:
```js
const getSections = R.propOr([], 'sections');
```
In most cases JSDoc looks like:
```js
/*
* @param {Object}
* @retrurns {Object[]}
*/
const getSections = R.propOr([], 'sections');
```
We want in the near future to move to TypeScript. But now we use it for code validation based on JSDoc comments and TypeScript think that we have not correct JSDoc (he's right).
Valid JSDoc:
```js
/*
* @param {Object} document
* @retrurns {Object[]}
*/
const getSections = R.propOr([], 'sections');
```
Well, with this rule we can rectify this situation.
> feat: Add "require-param-name" rule

- src/iterateJsdoc.js
- src/rules/checkTypes.js
- src/rules/newlineAfterDescription.js
- src/rules/requireDescriptionCompleteSentence.js
- src/rules/requireHyphenBeforeParamDescription.js
- test/rules/assertions/checkTypes.js
- test/rules/assertions/newlineAfterDescription.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireHyphenBeforeParamDescription.js
This pull request introduces two major changes:
* Fixers. The following rules are now fixable with `--fix`. This is Issue #53 
* check-types
* newline-after-description
* require-description-complete-sentence
* require-hyphen-before-param-description
* require-description-complete-sentence now checks that after a period there's an upper case letter. Before, it only checked the beginning of paragraphs.
All this new behavior is tested.
> Add fixers to some rules

- .README/rules/require-description-complete-sentence.md
Updates the documentation to match the [code](https://github.com/gajus/eslint-plugin-jsdoc/blob/master/src/rules/requireDescriptionCompleteSentence.js#L82). Notably, the doc used to say "lowercase" while the code is looking for "uppercase".
> Fixes the require-description-complete-sentence docs

- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
```
/**
* foo
*/
```
was supposed to be fixed to 
```
/**
* Foo.
*/
```
but actually was not fixed at all.
This PR solves that.
> Fix issue with complete sentence fixer

- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
This pull request introduces the following fixes/enhancements:
1. Added support for `@return`, `@arg` and `@argument` which are synonyms of `@returns`, `@param`.
2. Account for `?`, `!` and `:` as punctuation marks that end the sentence. See #16 .
3. Ignored all `{}` tags inside description. e.g. `{@see Class.Function}`.
> Improvements for RequireDescriptionCompleteSentence

- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
Fixed some edge cases and added tests for them.
> Edge cases in requireDescriptionCompleteSentence

- src/index.js
> Add 'recommended' config

- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
> Correctly escape strings inserted into RegExps

- .README/README.md
- .README/rules/no-undefined-types.md
- .README/rules/valid-types.md
- package.json
- src/index.js
- src/iterateJsdoc.js
- src/rules/checkTypes.js
- src/rules/noUndefinedTypes.js
- src/rules/validTypes.js
- test/rules/assertions/checkTypes.js
- test/rules/assertions/noUndefinedTypes.js
- test/rules/assertions/validTypes.js
- test/rules/index.js
* #52 
* #44 
* Added [Kuniwak/jsdoctypeparser](/Kuniwak/jsdoctypeparser) as a runtime dependency, for parsing types inside JSdoc tags.
* `check-types` now checks for inner types such as `Array<String>`. This is a **Breaking** change.
* Added rule `valid-types` that checks there are no syntax errors when parsing the type. example of error: `@param {Array<string} foo`
* Added rule `no-undefined-types` that checks all the types are defined in the scope, and marks types in JSdoc comments as used, so imports for types will not be marked as unused by `no-unused-vars`
**This is a breaking change**
> Added a type parser and two new rules for types in JSdoc comments

- src/rules/noUndefinedTypes.js
I've manually built and ran it on a large code base, so this should be the last crash to fix. sorry for the hassle.
> fix: no-undefined-types crashing when jsdoc has no tags

- README.md
- src/iterateJsdoc.js
- src/rules/requireParam.js
- test/rules/assertions/requireParam.js
This PR adds a new boolean setting called `allowOverrideWithoutParam` with a default value of `false`. 
- When the setting is `true`, the `@override` tag can be used without any accompanying `@param` tag(s).
- When the setting is omitted (or explicitly set to `false`), the original behavior remains, and `jsdoc/require-param` will flag an error when it finds an `@override` tag without the correct accompanying `@param` tags.
This was required due to the recommendations of the [Google JS style guide](https://google.github.io/styleguide/jsguide.html) ([here](https://google.github.io/styleguide/jsguide.html#features-functions-parameters), [here](https://google.github.io/styleguide/jsguide.html#jsdoc-method-and-function-comments), and [here](https://google.github.io/styleguide/jsguide.html#appen …
> Add an `allowOverrideWithoutParam` setting for `jsdoc/require-param`

- package.json
Fixes: https://github.com/gajus/eslint-plugin-jsdoc/issues/79
Through just a little brute forcing, I was able to find the required minimum version, which I'm bumping here in the peerdep.
As a result of this being the effective case right now, only "fixing" the package manager expectations, I'd like to consider this a semver MINOR.
> Upgrade eslint peer dep to actually required minimum

- src/iterateJsdoc.js
Fixes (at least in part): https://github.com/gajus/eslint-plugin-jsdoc/issues/48
I've always been a (little) annoyed that the jsdoc eslint warnings are noted at the top of the comment block rather than on the impacted lines. This allows rules to be able to opt into this by passing in a parsed comment line.
I'm unsure how to test this, based on the complexity of the functions. I can demonstrate this working in a forthcoming PR, however.
I consider this change to be semver MINOR.
> Add support for reporting individual lines of jsdoc infraction

- src/rules/checkTagNames.js
- src/rules/checkTypes.js
- src/rules/noUndefinedTypes.js
- src/rules/requireHyphenBeforeParamDescription.js
- src/rules/requireParamDescription.js
- src/rules/requireParamName.js
- src/rules/requireParamType.js
- src/rules/requireReturnsDescription.js
- src/rules/requireReturnsType.js
- src/rules/validTypes.js
- test/rules/assertions/checkTagNames.js
- test/rules/assertions/checkTypes.js
- test/rules/assertions/noUndefinedTypes.js
- test/rules/assertions/requireHyphenBeforeParamDescription.js
- test/rules/assertions/requireParamDescription.js
- test/rules/assertions/requireParamName.js
- test/rules/assertions/requireParamType.js
- test/rules/assertions/requireReturnsDescription.js
- test/rules/assertions/requireReturnsType.js
- test/rules/assertions/validTypes.js
Follows up on https://github.com/gajus/eslint-plugin-jsdoc/pull/82
This attempts to update all rules to attribute errors directly to the offending line rather than to the whole jsdoc block. There are several rules where specific lines are unknown (like the absence of a thing), or hard to figure (the last line of a description, or will be addressed later (checkParamNames).
I committed by rule changed, just for completeness.
I would suggest this change is MINOR
> Set line locations when reporting violations

- package.json
- Testing (Update): Deprecated Mocha --compilers flag; see https://github.com/mochajs/mocha/wiki/compilers-deprecation
> Change deprecated Mocha `compilers` flag to `require`

- README.md
- src/iterateJsdoc.js
- src/rules/requireParam.js
- test/rules/assertions/requireParam.js
I wasn't sure whether to add them as settings rather than rule-specific options, but I followed your pattern.
> Optionally loosen `requireParam` when implements/augments/extends present on tag or parent

- src/iterateJsdoc.js
`sourceCode.getJSDocComment` can return `null` here in case of incomplete or malformed JSDoc comment and this will result in ESLint crash
> Fix crash on invalid JSDoc class comment

- .README/README.md
- README.md
- Add docs missing for `allowImplementsWithoutParam` and `allowAugmentsExtendsWithoutParam`, and include them with `allowOverrideWithoutParam` (to save space and to mention that they all operate if present on the parent class comment block or the same comment block)
> Docs for `allowImplementsWithoutParam` and `allowAugmentsExtendsWithoutParam` and updating `allowOverrideWithoutParam`

- .README/README.md
- .README/rules/check-examples.md
- README.md
- src/index.js
- src/iterateJsdoc.js
- src/rules/checkExamples.js
- test/rules/assertions/checkExamples.js
- test/rules/index.js
- feat: Add `check-examples` rule to lint JavaScript within `@example` (fixes #101);
with settings to:
1. require JSDoc-spec'd `<caption>` at beginning of `@example`
2. regex settings to whitelist and blacklist lintable examples
3. setting for a dummy file name to trigger specific rules defined in one's
config; usable with ESLint `overrides`->`files` globs, to apply a desired
subset of rules with `@example` (besides allowing for rules specific to
examples, can be useful for using same rules within `@example` as
with JavaScript Markdown lintable by other plugins)
4. Other settings for specifying config (base config object or an `.eslintrc`
config file; checks normal `.eslintrc` by default unless
`eslintrcForExamples` setting is set to `false`)
5. Provides some defaults for suppressing …
> `check-examples` rule

- .README/README.md
- .README/rules/check-examples.md
- README.md
- src/iterateJsdoc.js
- src/rules/checkExamples.js
- test/rules/assertions/checkExamples.js
Thanks very much for all the reviews!
I realized after the fact that I should probably add this config as well. One [can't currently use multi-line comments](https://github.com/jsdoc3/jsdoc/issues/821) in JSDoc, and I haven't added any handling for them, but these will at least work with single-line comment config and allows for disabling. Admittedly inline config would probably be pretty unusual within examples anyways, but figured it should be exposed.
Also has two very minor clarifications in the README.
> - Add `allowInlineConfig` and `reportUnusedDisableDirectives`

- src/rules/checkParamNames.js
- test/rules/assertions/checkParamNames.js
Solves: #135.
This is by no means a perfect solution, but was a simple solution that wouldn't require considerable refactoring. This implementation allows for array value props to be defined.
A better solution would be one that checks that the `lastRealParameter` has the `Object[]` type.
Thank you for the excellent plugin! 👍
> Allow for array value props to be defined

- src/rules/requireReturns.js
- test/rules/assertions/requireReturns.js
Currently the requireReturns Rule indicates false positives in case you use the inherit documentation.
In a perfect world the inherited documentation should be checked. But the requireReturns Rule has no information about the inheritance. So disabling the Rule in case a jsdoc comment with a inherit tag was found seems to be the only viable solution. 
This pull request fixes #153.
> RequireReturns Rule does not honor inheritdoc tag.

- README.md
- src/rules/requireReturnsDescription.js
- test/rules/assertions/requireReturnsDescription.js
Fixes  #157 .
If the return type is `{void}` or `{undefined}`, return description is not required.
> feat: make require-returns-description accept void functions (fixes #157)

- .README/rules/check-tag-names.md
- README.md
- src/tagNames.js
Added `@generator`, `@package` and `@yields`, which are listed in http://usejsdoc.org/ .
>  feat: Update supported jsdoc tags (fixes #163)

- README.md
- src/iterateJsdoc.js
- src/rules/checkTypes.js
- test/rules/assertions/checkTypes.js
Previously when the tag is `@returns` or `@throws`, the
error message was `Invalid JSDoc @returns "" type "Number" .`.
Now the empty quotes are removed.
> Fix: correct error message of `check-types` (fixes #103)

- src/tagNames.js
Though this tag is not defined in jsdoc itself, it is used
by closure compiler and typescript.
> feat: add support for @template tag (fixes #165)

- src/rules/requireReturnsCheck.js
- test/rules/assertions/requireReturnsCheck.js
Abstract methods are typically completely documented as their children inherit their documentation by default. But their implementation is normally a single thow statement.
A perfect example can be found in the JSDoc Documentation:
http://usejsdoc.org/tags-abstract.html
The current eslint-plugin-jsdoc implementation fails in this case. It complains about a missing return statement. 
I also reordered the code and removed code which looks to me obsolete. I could not think of any example where the check for undefined or void code could kick into action. There is also no unit test which would cover this branch.
Futhermore I added a test which ensures at most one returns parameter is specified.
> Makes "Check Returns" ignore abstract methods.

- .README/README.md
- .README/rules/check-syntax.md
- README.md
- src/index.js
- src/rules/checkSyntax.js
- test/rules/assertions/checkSyntax.js
- test/rules/index.js
Reports against Google Closure Compiler syntax.
Only checks for `optional` style at the moment. Would be good to expand upon in the future / add optionals for `always-google-closure`, etc.
> feat: add rule check syntax

- .README/README.md
- .README/rules/check-indentation.md
- README.md
- src/index.js
- src/rules/checkIndentation.js
- test/rules/assertions/checkIndentation.js
- test/rules/index.js
Reports against extra indentation of eg; description blocks. Would be good to add optionals in the future to specify `allowed` and `max` levels of indentation.
Eg; Invalid:
```
/**
* Description line one
*                     line two
*/
```
> feat: add rule check indentation

- README.md
- package.json
- src/rules/checkIndentation.js
- test/rules/assertions/checkTypes.js
This PR shows that #133 is fixed, and that #145 is starting to be addressed.
However, it depends on Kuniwak/jsdoctypeparser#51 being merged and a new version of that package being published.
> Test typeof and import types from Typescript

- README.md
- src/rules/requireReturnsCheck.js
- test/rules/assertions/requireReturnsCheck.js
Fixes #142 .
Make require-returns-checks ignore absence of return
statement if jsdoc return type is `void` or `undefined`.
> fix: require-returns-check false positive

- src/rules/checkSyntax.js
- test/rules/assertions/checkSyntax.js
`jsdoc.tags` may be empty when there is a JSDoc-style comment but no tags present, so this fixes the error which occurs in this situation. It is also not necessary to check for `length` as the array iteration block that follows will not be entered upon an empty array.
> Fix: Avoid error for `check-syntax` when tags not present

- .README/rules/check-tag-names.md
- src/tagNames.js
- test/rules/assertions/checkTagNames.js
- test/rules/assertions/jsdoc3Tags.js
Per http://usejsdoc.org/tags-memberof.html , a syntax `@memberof!` (with an exclamation mark) is allowed.
> - Support `@memberof!`

- README.md
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/validTypes.js
- test/rules/assertions/validTypes.js
This PR adds behavior for these tags--currently within `valid-types` where I think it has bearing:
1. `@alias`, `@augments`, `@extends`, `@lends`, `@memberof`, `@memberof!`, `@mixes`, `@name`, `@this`
1. `@callback`, `@event`, `@listens`, `@fires`, `@emits`
1. `@borrows`
The following apply to the above sets:
- Expect tags in set 1 or 2 to have a valid namepath if present
- Prevent set 2 from being empty by setting `allowEmptyNamepaths` to `false` as these tags might have some indicative value without a path (but set 1 will always fail if empty)
- For the special case of set 3, i.e., `@borrows <that namepath> as <this namepath>`, check both namepaths are present and valid and ensure there is an `as ` between them.
> Check invalid and/or empty namepaths

- src/index.js
- src/rules/requireJSDoc.js
- test/rules/assertions/requireJSDoc.js
- test/rules/index.js
Implements a requireJSDoc compatible rule as described in issue #162.
The unit test file is ported from eslint and therefore MIT licensed for more details refer also to issue #162
> Implement a requireJSDoc compatible rule

- src/rules/checkTagNames.js
#184 added support for auto-fixing the `check-tag-names`, but it looks like the replacement is on the entire string, and not tag names specifically. This PR is to prefix the replacement with an `@` symbol to try and target tag names.
I'm not sure if it would be better to do a global find and replace so all tag names are updated, not just the first match? e.g. `new RegExp('@' + jsdocTag.tag, 'g')`
I was also looking to add tests, but I didn't see anything for the autofixes - if you have some guidance on how I might go about adding them, I'd be more than happy to.
> Prefix the tag name with an @ sign to avoid replacements in non-tag-names

- src/iterateJsdoc.js
- src/rules/requireJsdoc.js
- src/rules/requireReturnsCheck.js
- Change rule format (require-jsdoc already in this format and all other rules use iterateJsdoc.js) per issue #19
Fixes #19.
> Update to later ESLint rule format

- src/rules/checkTagNames.js
- test/rules/assertions/checkTagNames.js
Previously the report location is the entrie jsdoc.
Now the report location is the line of the tag.
> fix: make `checkTagNames` report position more precise

- README.md
- src/rules/noUndefinedTypes.js
- test/rules/assertions/noUndefinedTypes.js
- Consider Node.js/Commonjs as module (including variables in module scope as well as global)
- (Ensure all child scopes included if there can be more than 1)
- Testing: Add one test with node false and another with node true
Fixes #109.
> Ensure `no-undefined-types` catches modular scope for Node/commonjs env's

- README.md
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/requireReturns.js
- src/rules/requireReturnsCheck.js
- test/rules/assertions/requireReturns.js
- test/rules/assertions/requireReturnsCheck.js
This build's on @thsmi 's great work with #194, refactoring to use string literals in place of the string constants as requested.
I also switched arrow functions to object shorthand since there was no advantage to using arrow functions here; besides taking up slightly more space, they are less performant. (See https://medium.com/@charpeni/arrow-functions-in-class-properties-might-not-be-as-great-as-we-think-3b3551c440b1 )
Note that this also fixes #151, #158, #200 and #201.
> Rework require returns

- README.md
- src/iterateJsdoc.js
- src/rules/requireExample.js
- test/rules/assertions/requireExample.js
also skip if possesses `inheritdoc`/`override`
Fixes #40
> Avoid example on constructors

- src/eslint/LICENSE-MIT.txt
- src/eslint/getJSDocComment.js
- src/iterateJsdoc.js
Fixes #189.
(FWIW, I switched from `getClassJsdocNode` to `getClassNode` because of another PR coming which needed this lower level functionality anyways.)
> Integrate ESLint-deprecated `getJSDocComment`

- .babelrc
- package.json
closes #224
I think it's better to leave the task of adding codecov/coverall to the maintainer.
> build: add coverage in `npm test`

- src/rules/requireHyphenBeforeParamDescription.js
- For consistency with other rules, have `require-hyphen-before-param-description` check `tagNamePreference` setting (via `utils.getPreferredTagName`)
Pending any decision about https://github.com/gajus/eslint-plugin-jsdoc/issues/216#issuecomment-492897759 , I think the PR should be applied for consistency with the other param rules (and for easier finding of all the relevant rules if a change is made).
> `require-hyphen-before-param-description` and `tagNamePreference` setting

- .README/rules/valid-types.md
- src/jsdocUtils.js
- src/rules/noUndefinedTypes.js
- src/rules/validTypes.js
- Optimization: For `no-undefined-types`, only check tags expected to have types (as with `check-types`) or, for `valid-types`, tags expected to have types or namepaths
- Docs: For `valid-types`, indicate this grouping of name(path) defining vs. pointing tags
Fixes part of #233.
> Only check tags expected to have types for `no-undefined-types` and `valid-types`

- .eslintrc.json
- package.json
- src/jsdocUtils.js
- test/.eslintrc.json
- npm: Update devDeps and peerDep (breaking change?)
- Linting: Disable two new rules; prefer `includes`
I ran `npm-check-updates` and found the devDep items in the PR ready for updates.
It also updated the peerDependency, eslint. I don't know if you'd consider that a breaking change, since it will probably only alert users rather than require them to use eslint 5, but I figure it may be time for a change?
> npm updates

- src/iterateJsdoc.js
- src/rules/checkExamples.js
- test/rules/assertions/checkExamples.js
While I know I could create config to determine at what level the rule follows, I think it may be better for us to settle on a project-wide approach. In the meantime, I think it makes sense for `check-examples` to work on classes as well as functions.
> Change behavior of check-examples to also check classes

- .README/rules/require-description.md
- README.md
- src/iterateJsdoc.js
- src/rules/requireDescription.js
- test/rules/assertions/requireDescription.js
Add options `contexts` and `noDefaults` to `require-description` to allow additional contexts (e.g., `ClassDeclaration`); fixes #90
> `require-description` in additional contexts

- .README/README.md
- .README/rules/implements-on-classes.md
- README.md
- src/index.js
- src/rules/implementsOnClasses.js
- test/rules/assertions/implementsOnClasses.js
- test/rules/index.js
- Add rule `implements-on-classes` to prevent @implements on non-constructor functions; fixes #218
@sandersn
> Prevent `@implements` on non-constructor functions

- src/rules/checkAlignment.js
- src/rules/checkExamples.js
- src/rules/checkIndentation.js
- src/rules/checkParamNames.js
- src/rules/checkSyntax.js
- src/rules/checkTagNames.js
- src/rules/checkTypes.js
- src/rules/implementsOnClasses.js
- src/rules/matchDescription.js
- src/rules/newlineAfterDescription.js
- src/rules/noUndefinedTypes.js
- src/rules/requireDescription.js
- src/rules/requireDescriptionCompleteSentence.js
- src/rules/requireExample.js
- src/rules/requireHyphenBeforeParamDescription.js
- src/rules/requireParam.js
- src/rules/requireParamDescription.js
- src/rules/requireParamName.js
- src/rules/requireParamType.js
- src/rules/requireReturns.js
- src/rules/requireReturnsCheck.js
- src/rules/requireReturnsDescription.js
- src/rules/requireReturnsType.js
- src/rules/validTypes.js
As per https://eslint.org/docs/developer-guide/working-with-rules#rule-basics .
Not sure how this may be surfaced, but figure it doesn't hurt to document it.
> - Add `meta.type`

- .README/README.md
- .README/rules/no-types.md
- .README/rules/valid-types.md
- src/index.js
- src/rules/noTypes.js
- test/rules/assertions/noTypes.js
- test/rules/index.js
- Enhancement: Rule to prevent types on @param/@returns (Fixes #134)
- Docs: Clarify how sentence above preceding list continues
> - Enhancement: Rule to prevent types on `@param`/`@returns`

- src/rules/matchDescription.js
- src/rules/newlineAfterDescription.js
- src/rules/requireDescription.js
- src/rules/requireHyphenBeforeParamDescription.js
The schema should, per the [ESLint docs](https://eslint.org/docs/developer-guide/working-with-rules#rule-basics), "prevent invalid rule configurations", so this is more than just informative meta-data as well (`require-jsdoc` already had one).
> Meta.schema

- .README/README.md
- .README/rules/check-types.md
- .README/rules/no-undefined-types.md
- README.md
- src/iterateJsdoc.js
- src/rules/checkTypes.js
- src/rules/noUndefinedTypes.js
- test/rules/assertions/checkTypes.js
- test/rules/assertions/noUndefinedTypes.js
- Change: `check-types` will now include the preferred type in its report message
- Change: `no-undefined-types` now automatically allows `NaN` and `Infinity` types
- Enhancement: `check-types` and `no-undefined-types`: utilize `settings.jsdoc.preferredTypes` map
- Enhancement: `check-types`: Add option object with `noDefaults`
- Enhancement: `no-undefined-types`: Add option object with `preferredTypesAreDefined` and `definedTypes`
- Docs: `no-undefined-types`: Mention role of globals
Closes #107, #164, #166, #215 .
Also unblocks the one item I think is remaining for #1 , namely to correlate our new `preferredTypes` to eslint's deprecated `valid-jsdoc`.
Regarding #164, @gajus, I wonder if you want to also make a breaking change to the default behavior and require `object` instead of …
> `preferredTypes`

- .README/rules/check-types.md
- README.md
- src/rules/checkTypes.js
- test/rules/assertions/checkTypes.js
BREAKING CHANGE: `check-types` now expects "object" instead of "Object"
Makes consistent with Typescript recommendation and fact that `Object.create(null)` is not `instanceof Object` but its `typeof` is `object`.
Can restore old behavior through `settings: {jsdoc: {preferredTypes: {object: 'Object'}}}}` (and `check-types` still enabled). Closes #164
> `check-types` now expects "object" instead of "Object"

- .README/README.md
- README.md
- src/rules/checkTypes.js
- test/rules/assertions/checkTypes.js
enhancement(check-types): Allow `replacement` in place of `preferredType` for parity with supplied argument of the same name
> - `check-types`: Allow `replacement` in place of `preferredType`

- .README/README.md
- .README/rules/check-types.md
- README.md
- src/rules/checkTypes.js
- test/rules/assertions/checkTypes.js
This PR fixes #87 - allowing one to forbid or rename types which are too generic, e.g., `Array`, `Promise`, or `Object` and have no child types specified.
----
BREAKING CHANGE: Cause `preferredTypes` setting not to apply by default to parent types; need to target type name with "<>" appended to target parent types (and only parent types); can alternatively; also adds option `unifyParentAndChildTypeChecks` to restore the old behavior
Allows for warning against overly generic types only (e.g., `Array` without its own children) or against the parent type only (to disallow `Array.<someType>`)
To restore old behavior, also target type names with "<>" or set the `unifyParentAndChildTypeChecks` option.
> Change `preferredTypes` to require "<>" be appended to types by default in order to apply to parent types and otherwise apply them to child types only

- .README/README.md
- README.md
- src/iterateJsdoc.js
- src/rules/requireDescription.js
- src/rules/requireExample.js
- src/rules/requireParam.js
- src/rules/requireReturns.js
- test/rules/assertions/requireParam.js
When working on the `require-param` rule, I added some settings which now, in light of considering the other require-tag-presence-on-function rules (`require-description`, `require-returns`, and `require-example`), I believe it makes more sense to have generic rules to describe how `@override`, `@augments`/`@extends`, and `@implements` should behave, as the expectations are likely to be similar.
----
feat: add settings `overrideReplacesDocs`, `augmentsExtendsReplacesDocs`, `implementsReplacesDocs` and apply to  `require-param`, `require-description`, `require-example`, and `require-returns` for exempting all of these from errors in the case of the presence of `@override`, `@augments`/`@extends`, or `@implements`, respectively.
This commit also adds the following new behavior: with …
> Deprecate param-specific settings to avoid docs in favor of generic ones

- README.md
- src/rules/requireHyphenBeforeParamDescription.js
- test/rules/assertions/requireHyphenBeforeParamDescription.js
* fixes fixer for `require-hyphen-before-param-description`: reads the actual line of the problematic jsdocTag and inserts a hyphen before the description.
Hopefully closes #176.
> Fix fixer for `require-hyphen-before-param-description`

- README.md
- src/rules/requireHyphenBeforeParamDescription.js
- test/rules/assertions/requireHyphenBeforeParamDescription.js
Thank you for the quick response to #265, but it appears I haven't tested thoroughly. Sincerest apologies!
This PR fixes hyphen insertion for the following cases:
* Parameter name and description are equal
```
/*
*@param foo foo
*/
function () {}
```
by replacing the *last* occurrence in a line, not the *first*.
* Multiline descriptions
```
/*
* @param foo single line
* another line
*/
function () {}
```
by replacing the (last occurrence of (the first line of the description)) in a line.
That's a mouthful :/
Hopefully this will have covered all cases. Please let me know if I've missed anything.
> Fix fixer for require-hyphen-before-param-description

- README.md
- package.json
- src/eslint/getJSDocComment.js
- test/rules/assertions/requireParam.js
fixes #182
This commit introduces `babel-eslint` as a dependency, otherwise optional chaining cannot be tested.
> fix: false positive with optional chaining

- .README/README.md
- .README/rules/check-types.md
- README.md
- package.json
- src/rules/checkTypes.js
- src/rules/noUndefinedTypes.js
- test/rules/assertions/checkTypes.js
- test/rules/assertions/noUndefinedTypes.js
BREAKING CHANGE: change `<>` to no longer apply to `SomeType.<>` but instead to now support `SomeType<>`
feat: pseudo-type `[]` to catch parent array types of form `string[]`, `number[]`, etc.
feat: support `.<>` as separate type
fix: ensure working with nested type arrays/objects
fix: ensure fixer preserves angle-bracket-dot or square bracket notation for arrays/objects
chore: Update husky, semantic-release devDeps; add `typescript` devDep for `type-fest` peer dep. (used indirectly by husky and semantic-release)
Breaking change through `jsdoctypeparser` update.
----
Also includes a minor adjustment to `no-undefined-types` to be able to recognize types suffixed with the pseudo-types (e.g., `<>`).
~This is currently being blocked by …
> `check-types`: Distinguish `.<>` from `<>`; support `[]`; check/fix nested array/object types

- src/iterateJsdoc.js
It is fine to pass `{fix: null}` to  `context.report()`.
> chore: simplify report()

- src/iterateJsdoc.js
- src/rules/checkExamples.js
- src/rules/requireExample.js
- src/rules/requireReturns.js
Settings are now accessed from `settings.<thing>` instead of `utils.<thing>()`.
> chore: move utils.<someSetting> to settings.<someSetting>

- README.md
- src/rules/requireParam.js
- src/rules/requireReturns.js
- test/rules/assertions/requireParam.js
- test/rules/assertions/requireReturns.js
> fix: Stop warning missing param and returns tags if `@type` is present

- .README/README.md
- .README/rules/require-jsdoc.md
- README.md
- package.json
- src/exportParser.js
- src/rules/requireJsdoc.js
- test/rules/assertions/requireJsdoc.js
This PR adds support for configuring require-jsdoc rule to require JSDoc comments for exported function bodies only. There are options for configuring the export checks for CommonJS and ES6 exports.
Fixes #192
> Add exported functions option to require-jsdoc rule

- src/rules/newlineAfterDescription.js
- src/rules/requireDescription.js
- src/rules/requireExample.js
- src/rules/requireHyphenBeforeParamDescription.js
- src/rules/requireParam.js
- src/rules/requireReturns.js
This pr moves misplaced `schema`s to inside of `meta`. Otherwise these schemas are ineffective, that is, eslint engine does not validate options.
> fix: make options schemas effective

- README.md
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/noUndefinedTypes.js
- test/rules/assertions/noUndefinedTypes.js
This pull request adds support for Google Closure Compiler [Generic (aka Template) types](https://github.com/google/closure-compiler/wiki/Generic-Types) to `no-undefined-types`.
Makes the following code valid:
```js
/**
* @template TEMPLATE_TYPE
*/
class Foo {
/**
* @return {TEMPLATE_TYPE}
*/
bar () {
}
}
```
While previously `no-undefined-types` reported `TEMPLATE_TYPE` in `bar` as undefined.
> no-undefined-types: Treat GCC generic types as defined

- README.md
- src/rules/requireReturnsCheck.js
- test/rules/assertions/requireReturnsCheck.js
As per jsdoc `@interface` tag [description](https://devdocs.io/jsdoc/tags-interface), class marked with this tag should denote that all members of the class are interface symbols and therefore functions can have `@returns` tag, but no function body with `return` statement.
This pull request makes the following code valid:
```js
/**
* @interface
*/
class Foo {
/**
* @returns {string}
*/
bar () {}
}
```
While previously `require-returns-check` reported `bar` as missing return value;
> require-returns-check: Skip interface class methods

- .README/rules/require-jsdoc.md
- README.md
- src/exportParser.js
- src/rules/requireJsdoc.js
- test/rules/assertions/requireJsdoc.js
feat(require-jsdoc): allow `require` to posses `ClassExpression` boolean property
I think this is a harmless option addition, but thought I'd confirm with a PR as it is a new feature...
> `ClassExpression` with `require`/`pubilcOnly`

- src/iterateJsdoc.js
Avoid passing `ancestors` and `sourceCode` because they can be derived from `context`. `curryUtils` is renamed to `getUtils` because there is no curry in it.
> refactor: simplify curryUtils and rename it

- .README/rules/check-indentation.md
- .README/rules/check-syntax.md
- .README/rules/check-tag-names.md
- .README/rules/check-types.md
- .README/rules/newline-after-description.md
- .README/rules/no-undefined-types.md
- .README/rules/require-description-complete-sentence.md
- .README/rules/require-hyphen-before-param-description.md
- .README/rules/valid-types.md
- README.md
- src/iterateJsdoc.js
- src/rules/checkAlignment.js
- src/rules/checkIndentation.js
- src/rules/checkSyntax.js
- src/rules/checkTagNames.js
- src/rules/checkTypes.js
- src/rules/newlineAfterDescription.js
- src/rules/requireDescriptionCompleteSentence.js
- src/rules/requireHyphenBeforeParamDescription.js
- src/rules/validTypes.js
- test/rules/assertions/checkAlignment.js
- test/rules/assertions/checkIndentation.js
- test/rules/assertions/checkTagNames.js
- test/rules/assertions/checkTypes.js
BREAKING CHANGE: previously rules mostly works only on function-like
nodes, now a subset of rules are updated to work on **all** JSDocs.
Fixes #214
> feat: make some rules work on non-functions

- .README/rules/match-description.md
- .README/rules/require-description.md
- .README/rules/require-jsdoc.md
- README.md
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/matchDescription.js
- src/rules/requireDescription.js
- src/rules/requireJsdoc.js
- test/rules/assertions/matchDescription.js
- test/rules/assertions/requireDescription.js
- test/rules/assertions/requireJsdoc.js
- BREAKING CHANGE(require-description): remove `noDefaults` option and change `contexts` to always override defaults
- feat(match-description): allow `mainDescription: string|boolean` to override or disable main description separate from default
- feat(match-description): add `contexts` options for control on which contexts the rules apply
- feat(match-description): report line number with `match-description`
- feat(match-description): allow reporting multiple errors when main description validation fails
- feat(require-jsdoc): add `contexts` option to allow working with any node type
- fix(match-description, require-description): allow `contexts` to work with any node type
- fix(match-description): tighten default regex to require punctuation at the end even if only a single character
> match-description options

- .README/README.md
- README.md
- package.json
- src/iterateJsdoc.js
- src/rules/checkExamples.js
- src/rules/checkParamNames.js
- src/rules/checkTagNames.js
- src/rules/requireDescription.js
- src/rules/requireHyphenBeforeParamDescription.js
- src/rules/requireParam.js
- src/rules/requireParamDescription.js
- src/rules/requireParamName.js
- src/rules/requireParamType.js
- src/rules/requireReturns.js
- src/rules/requireReturnsCheck.js
- src/rules/requireReturnsDescription.js
- src/rules/requireReturnsType.js
- test/rules/assertions/checkParamNames.js
- test/rules/assertions/checkTagNames.js
- test/rules/assertions/requireDescription.js
- test/rules/assertions/requireHyphenBeforeParamDescription.js
- test/rules/assertions/requireParam.js
- test/rules/assertions/requireParamDescription.js
- test/rules/assertions/requireParamName.js
- test/rules/assertions/requireParamType.js
- test/rules/assertions/requireReturns.js
- test/rules/assertions/requireReturnsCheck.js
- test/rules/assertions/requireReturnsDescription.js
- test/rules/assertions/requireReturnsType.js
feat(check-tag-names): allow rejecting normally valid tag names and/or providing custom error messages when suggesting tags to reject or replace (fixes #108)
Reporting normally valid tags may be of interest for tags like `@todo`. This is implemented by allowing the user to set targeted `tagNamePreference` tags to `false` or to an object with only a `message` and no `replacement`
Custom messages for `check-tag-names` are implemented by allowing the user to set  targeted `tagNamePreference` tags to an object with `message` and `replacement` (mirroring `preferredTypes` behavior). Note that for other rules leveraging `tagNamePreference` (via `utils.getPreferredTagName`) to find the user's preferred tag name, the `replacement` will be used in the likes of error messages but not the `message`. …
> Allow rejecting normally valid tag names and/or providing custom error messages when suggesting tags to reject or replace

- .README/README.md
- README.md
- src/rules/checkTypes.js
- test/rules/assertions/checkTypes.js
fix(check-types): remove template substitution variables, `badType`, `preferredType`, and `replacement`
In place of the substitution variables, one must now hard-code the type in the message
> Remove pre-existing template substitution in `check-types` per #302

- .README/rules/require-description-complete-sentence.md
- README.md
- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
feat(require-description-complete-sentence): validate explicit `description` tags
Fixes part of #301 to add checks on explicit `@description` tags (as already done for implicit jsdoc block ones and param/returns descriptions).
> require-description-complete-sentence explicit `@description` tag validation

- .README/rules/match-description.md
- README.md
- src/rules/matchDescription.js
- test/rules/assertions/matchDescription.js
feat(match-description): allow `description` and `desc` tags to be matched for validation
Fixes part of #301. This expands the tags that can be validated through the existing `tags` option to include `@description`/`@desc` tags.
> `match-description`

- .README/README.md
- .README/rules/require-example.md
- .README/rules/require-jsdoc.md
- .README/rules/require-returns.md
- .README/rules/valid-types.md
- README.md
- src/iterateJsdoc.js
- src/rules/requireExample.js
- src/rules/requireJsdoc.js
- src/rules/requireReturns.js
- src/rules/validTypes.js
- src/warnRemovedSettings.js
- test/rules/assertions/requireExample.js
- test/rules/assertions/requireJsdoc.js
- test/rules/assertions/requireReturns.js
- test/rules/assertions/validTypes.js
Fixes part of #216.
This pr moves some settings to rule options. When a removed setting is set, a warning or error will be reported.
Does not move settings for `check-examples` because it is too much work.
BREAKING CHANGE: The following settings has been removed and became options
under relevant rules.
* `settings.jsdoc.allowEmptyNamepaths` -> option in `valid-types`
* `settings.jsdoc.checkSeesForNamepaths` -> option in `valid-types`
* `settings.jsdoc.exemptEmptyFunctions` -> option in `require-jsdoc`
* `settings.jsdoc.forceRequireReturn` -> option in `require-returns`
* `settings.jsdoc.avoidExampleOnConstructors` -> option in `require-example`
> Move settings to options

- .README/README.md
- README.md
- package.json
- src/iterateJsdoc.js
- src/rules/requireParam.js
- test/rules/assertions/requireParam.js
feat(`require-param`): remove deprecated settings `allowOverrideWithoutParam`, `allowImplementsWithoutParam`, `allowAugmentsExtendsWithoutParam`
Removes the following settings in favor of mentioned replacements settings:
- `settings.jsdoc.allowOverrideWithoutParam` - replaced by `settings.jsdoc.overrideReplacesDocs`
- `settings.jsdoc.allowImplementsWithoutParam` - replaced by `settings.jsdoc.implementsReplacesDocs`
- `settings.jsdoc.allowAugmentsExtendsWithoutParam` - replaced by `settings.jsdoc.augmentsExtendsReplacesDocs`
> Remove deprecated settings specific to `require-param`

- .README/rules/match-description.md
- README.md
- src/rules/matchDescription.js
- test/rules/assertions/matchDescription.js
feat(`match-description`): allow arbitrary tags; also fixes `returns`/`return` to avoid skipping matching of an initial "name" and space
The one disadvantage here is that because `tags` is an option instead of a setting, adding arbitrary tags doesn't make them automatically available to `check-tag-names` as well.
Also helps users work around lack of #233 support.
> Allow `match-description` to apply to descriptions of arbitrary tags

- .README/rules/require-description.md
- README.md
- src/rules/requireDescription.js
- test/rules/assertions/requireDescription.js
~feat(`require-description`): add `matchImplicit` option to accept implicit descriptions as satisfying the rule (fixes #301)~
feat(`require-description`): add `descriptionStyle` option to accept implicit descriptions as satisfying the rule by default (fixes #301)
To restore old behavior, set the option `descriptionStyle` to `"tag"`
----
Other alternatives would be to allow implicit descriptions (i.e., jsdoc blocks with any non-tag intro text) as satisfying this rule by default. An advantage of such an approach would be that it would more closely match how `match-description` and `require-description-complete-sentence` behave as they automatically check both implicit and explicit descriptions now.
But since people have been using the `require-description` rule so far to …
> `matchImplicit` option for `require-description`

- .README/rules/require-example.md
- README.md
- src/rules/requireExample.js
- test/rules/assertions/requireExample.js
feat(`require-example`): add `contexts` array option (of AST types) to allow overriding enforced contexts (fixes #273)
> `require-example`: add `contexts` option

- src/rules/checkTagNames.js
- test/rules/assertions/checkTagNames.js
This fix assumes that all tagNames are followed with a space, would that be correct?
> fix(checkTagNames): #327 - Tag name autofix confused by adjacent tags

- .README/rules/require-description-complete-sentence.md
- README.md
- src/jsdocUtils.js
- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
feat(require-description-complete-sentence): limit checking to certain default tags likely to have descriptions or by `tags` array for additional choices; fixes #337
Tags that are checked for description by default are: 'param', 'arg', 'argument', 'property', 'prop', 'returns', 'return', 'summary', 'file', 'fileoverview', 'overview', 'classdesc', 'todo', 'deprecated', 'throws', 'exception', 'yields', 'yield'. Note that `see` and `copyright` are not included by default because of potentially allowing a non-description or potential sensitivity, respectively.
> `require-description-complete-sentence`: limit checking by default to likely tags and new option array

- README.md
- src/iterateJsdoc.js
- src/rules/checkParamNames.js
- src/rules/checkTagNames.js
- src/rules/matchDescription.js
- src/rules/requireDescription.js
- src/rules/requireDescriptionCompleteSentence.js
- src/rules/requireParam.js
- src/rules/requireReturns.js
- src/rules/requireReturnsCheck.js
- test/rules/assertions/implementsOnClasses.js
- test/rules/assertions/matchDescription.js
- test/rules/assertions/requireDescription.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
Fixes for #332 (Grouping into PR for association of related commits)
> Tag name preference

- README.md
- src/bin/readme-assertions.js
- test/rules/assertions/checkExamples.js
Because of this issue(trim bug in trimCode) - #340, I fixed it.
> fix: Fix trim bug in trimCode

- README.md
- src/bin/readme-assertions.js
- test/rules/assertions/noUndefinedTypes.js
- test/rules/assertions/requireJsdoc.js
- test/rules/assertions/requireReturns.js
1. Fix: ```trimCode() ```- exclude zero size slicing
2. Fix: wrong alignment in ```test/rules/assertions/*.js```
> fix: Fix wrong alignment

- README.md
- src/rules/requireParam.js
- test/rules/assertions/requireParam.js
This is the fixing, what i mentioned in #347 
If there is no reason not to fix [it](#347)
I think this change is reasonable.
But If there are specific reasons, please ignore this PR. Thanks!
> fix(require-param): reporting all missing jsdoc params

- src/rules/noTypes.js
- test/rules/assertions/noTypes.js
* Add fixer for no-types using reportJSDoc()-  #336
> feat: add fixer for no-types

- README.md
- src/eslint/getJSDocComment.js
- src/iterateJsdoc.js
- src/rules/requireJsdoc.js
- test/eslint/getJSDocComment.js
- test/rules/assertions/requireJsdoc.js
> feat: allow empty line between jsdoc and jscode

- src/rules/requireJsdoc.js
- test/rules/assertions/requireJsdoc.js
fix: avoid highlighting whole function block upon missing jsdoc block in favor of highlighting first line only; fixes #386
I'm calling it a "fix" as it is not really a new feature, and more of fixing an annoyance, though it's kind of change in behavior a little, so requesting your review, @golopot .
> `require-jsdoc`: Highlight first line only of missing jsdoc

- .README/rules/check-indentation.md
- README.md
- src/rules/checkIndentation.js
- test/rules/assertions/checkIndentation.js
This should fix ~#334~ by making `check-indentation` rule ignore whole `@example` blocks.
UPDATE: actually it does not fix #334, but it fixes similar issue with example code blocks.
It could be improved to allow to pass which tags should be ignored as an option, instead of rather specific `excludeExamples` i added.
> Fix: ignore examples in `check-indentation`

- .README/rules/check-indentation.md
- README.md
- src/rules/checkIndentation.js
- test/rules/assertions/checkIndentation.js
This should fix #334.
~It builds on top of #388, to prevent merge conflicts later, if both are to be merged.~ #388 was merged, this one was rebased on latest master.
> Fix #334: ignore code blocks in check-indentation

- src/rules/requireParam.js
- test/rules/assertions/requireParam.js
> feat(require-param): add fixer

- .README/rules/check-tag-names.md
- README.md
- src/jsdocUtils.js
- src/tagNames.js
feat(`check-tag-names`): allow undocumented jsdoc `modifies` tag and missing closure tags
This doesn't yet add support for #356 `settings.jsdoc.mode` but it moves toward that by distinguishing the source of the tags in source.
> allow undocumented jsdoc `modifies` tag and missing closure tags

- README.md
- src/iterateJsdoc.js
- src/rules/requireParam.js
- test/rules/assertions/requireParam.js
* @brettz9 - [ This is PR for 1, 2](https://github.com/gajus/eslint-plugin-jsdoc/issues/336#issuecomment-541258157)
> feat(`require-param`): change fixer to fix all missing tags at once

- README.md
- src/iterateJsdoc.js
- src/rules/checkAlignment.js
- test/rules/assertions/checkAlignment.js
addresses #368 
There were a few other areas where `' '.repeat` is used that probably need to be looked into further, as I believe they apply to rules other than "check-alignment".
> fix: Alignment fixer should use indentation character from sourceCode.

- .README/README.md
- .README/rules/check-tag-names.md
- README.md
- src/WarnSettings.js
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/warnRemovedSettings.js
- test/jsdocUtils.js
- test/rules/assertions/checkTagNames.js
feat(`check-tag-names` and other rules): begin `settings.jsdoc.mode`; utilize in `getPreferredTagName`, `isValidTag`, `getTagsByType`; fixes part of #356
BREAKING CHANGE: Allowable values: jsdoc|typescript|closure
I don't like the relatively large list of tags added to the README, but I also don't like not testing them so not sure if there is a better approach.
> Begin `settings.jsdoc.mode` (`check-tag-names` and others indirectly)

- .README/README.md
- .README/rules/check-types.md
- .README/rules/no-undefined-types.md
- .README/rules/valid-types.md
- README.md
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/checkTypes.js
- src/rules/noUndefinedTypes.js
- src/rules/validTypes.js
- test/rules/assertions/validTypes.js
Builds on #400; fixes part of #356
> Mode types

- .README/README.md
- .README/rules/no-undefined-types.md
- README.md
- src/rules/noUndefinedTypes.js
- test/rules/assertions/noUndefinedTypes.js
feat(`no-undefined-types`): only check `@template` in `no-undefined-types` for types in "closure" and "typescript" modes; fixes part of #356
`@template` has no special meaning for regular jsdoc, so don't check in "jsdoc" mode.
> Only check `@template` in `no-undefined-types` for types in "closure" and "typescript" modes

- README.md
- src/eslint/getJSDocComment.js
- test/eslint/getJSDocComment.js
- test/rules/assertions/checkExamples.js
Often it is required to disable linting in-between the JSDoc and the
code. This PR allows that to happen.
Without the following change the `jsdoc/require-jsdoc` rule needs to be
constantly disabled.
Consider the following example:
```ts
/**
* A user.
* @interface User
*/
interface User {
/**
* The users age.
* @type {number}
* @memberof User
*/
age: number;
/**
* The users name.
* @type {string}
* @memberof User
*/
name: string;
}
/**
* Determine if the provided value is a `User`;
* @param {*} user The value to check.
* @returns {boolean} Whether or not the provided value is a `User`.
*/
// Allow the Function to check any input.
// tslint:disable-next-line: no-any
function isUser(user: any): user is User {
if (user == null) {
return false;
}
const { age, name } = user;
if (typeof age !== …
```
> feat(`getJSDocComment`): ignore line comment

- .README/README.md
- .README/rules/check-access.md
- .README/rules/check-values.md
- .README/rules/empty-tags.md
- README.md
- package.json
- src/index.js
- src/iterateJsdoc.js
- src/rules/checkAccess.js
- src/rules/checkValues.js
- src/rules/emptyTags.js
- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/checkAccess.js
- test/rules/assertions/checkValues.js
- test/rules/assertions/emptyTags.js
- test/rules/index.js
feat(check-values): Add new rule for checking special tag values (within `version`, `since`, `license`, `author`)
Adds to `recommended`.
1. `@version` - Checks that there is a present and valid
[semver](https://semver.org/) version value.
2. `@since` - As with `@version`
3. `@license` - Checks that there is a present and valid SPDX identifier
or is present within an `allowedLicenses` option.
4. `@author` - Checks there is a value present, and if the option
`allowedAuthors` is present, ensure that the author value is one
of these array items.
> feat(check-values): Add new rule for checking special tag values

- .README/README.md
- .README/rules/empty-tags.md
- README.md
- src/index.js
- src/iterateJsdoc.js
- src/rules/emptyTags.js
- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/emptyTags.js
- test/rules/index.js
Added rule to `recommended`.
May add additional tags to check for emptiness using `tags` option.
> feat(`empty-tags`): expect certain tags to be empty

- .README/README.md
- .README/rules/check-access.md
- .README/rules/empty-tags.md
- README.md
- src/index.js
- src/iterateJsdoc.js
- src/rules/checkAccess.js
- src/rules/emptyTags.js
- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/checkAccess.js
- test/rules/assertions/emptyTags.js
- test/rules/index.js
BREAKING CHANGE: New rule updates `recommended`
Checks `@access` for allowed values and prohibits multiple access modifier tags on the same block
> feat(`check-access`): add rule to check access levels

- .README/rules/check-values.md
- README.md
- src/rules/checkValues.js
- test/rules/assertions/checkValues.js
feat(`check-values`): add `licensePattern` option to allow delimiting portion of license description to extract
Thereby can allow extra descriptive text before or after a license pattern.
> `check-values`: add `licensePattern` option

- README.md
- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
Currently it is possible to experience a false positive with the
`jsdoc/require-description-complete-sentence` rule.
The false positive is caused by starting a new line with a capital
letter when the previous line does not end with a period. Normally, this
is the correct behaviour, however, English sentences are more nuanced
than that.
The problem arises when using a word that starts with a capital letter
that just so happens to be at the start of a line. For instance, `I`, or
a programmatic word like `XMLHttpRequest`.
This PR tightens the constraint of the `isNewLinePrecededByAPeriod`
Function by checking for a lowercase letter immediately after an
uppercase letter.
This will still produce false positives if the new line starts with
`UserInterface` for example.
> feat(`require-description-complete-sentence`): tighten constraint

- .README/rules/check-examples.md
- README.md
- src/rules/checkExamples.js
- test/rules/assertions/checkExamples.js
With initial newlines now being considered as part of the example code (as of v18.1.6), the rule
may be problematic for projects which use an initial newline just to start an example
(and projects may wish to use extra lines within examples just for easier illustration
purposes), so this PR disables by default.
> feat(`check-examples`): add `no-multiple-empty-lines` by default

- README.md
- src/eslint/getJSDocComment.js
- src/iterateJsdoc.js
- src/jsdocUtils.js
- test/rules/assertions/noUndefinedTypes.js
In attempt to fix #363 I changed the way iterating over jsdoc comments works.
Previously, `iterateJsdoc` walked over comment nodes and processed them without regards of their context and most importantly, the AST node they're describing.
I changed this to iterate overs all js AST nodes, then selecting ones that have JSDoc comments and processing those along with js their node. This allowed to implement `getClassNode` properly and should probably allow more context-aware checks.
Some JSDoc comments are not associated with any nodes however and so they warranted a second pass on `Program:exit`.
Also `getJSDocComment` attributes JSDoc to several nodes, for example here:
```js
/**
* Comment.
*/
const foo = {
bar: 'baz'
}
```
`getJSDocComment` will return the JSDoc node for both `Identifier` …
> Refactor jsdoc iteration to walk through nodes comments are associated with

- .README/rules/check-param-names.md
- README.md
- src/rules/checkParamNames.js
- test/rules/assertions/checkParamNames.js
feat(`check-param-names`): add option `allowExtraTrailingParamDocs` to avoid reporting additional `@param`'s beyond actual function's arguments; fixes #450
> `check-param-names`: `allowExtraTrailingParamDocs` option

- .README/README.md
- .README/rules/require-file-overview.md
- README.md
- src/index.js
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/requireFileOverview.js
- test/rules/assertions/requireFileOverview.js
- test/rules/index.js
Report when `@file` (or if stated under `settings.jsdoc.tagNamePreference` as `@overview` or `@fileoverview`) is missing, duplicated, or preceded by anything besides a comment.
Fixes #55 .
> Require file overview

- .README/rules/require-description-complete-sentence.md
- README.md
- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
feat(`require-description-complete-sentence`): add `abbreviations` option; fixes #424
I haven't added any abbreviations by default, figuring we might first get some experience with it. But I've added a fair number of test cases (and if we do change the default, then the tests I added at least will need abbreviations specifically disabled).
> `require-description-complete-sentence`: `abbreviations` option

- .README/rules/check-types.md
- README.md
- src/rules/checkTypes.js
- test/rules/assertions/checkTypes.js
feat(`check-types`): add option `exemptTagContexts` to exempt type-checking (certain types or any types) on specific tags; fixes #255
> `check-types`: add `exemptTagContexts` option

- .README/README.md
- README.md
- src/iterateJsdoc.js
- test/rules/assertions/checkAlignment.js
- test/rules/assertions/requireParam.js
feat(`check-access`): allow `ignorePrivate` setting to work with `access private` tag.
Test a rule with `iterateAllJsocs` and without.
Currently only works with `@private` tag. `@access private` is equivalent.
> `check-access` allow `ignorePrivate` setting to work with `access private` tag

- .README/rules/match-description.md
- .README/rules/require-description.md
- .README/rules/require-example.md
- README.md
- src/iterateJsdoc.js
- src/rules/requireJsdoc.js
- test/rules/assertions/matchDescription.js
- test/rules/assertions/requireDescription.js
- test/rules/assertions/requireExample.js
- test/rules/assertions/requireJsdoc.js
feat(match-description, require-description, require-example): allow "any" for `contexts`; fixes #325
Since it would have required additional refactoring, I decided against applying to require-jsdoc, for which it would be pretty unusual anyways.
> `match-description`, `require-description`, `require-example`: "any" for `contexts`

- .README/rules/implements-on-classes.md
- .README/rules/no-types.md
- .README/rules/require-param-description.md
- .README/rules/require-param-name.md
- .README/rules/require-param-type.md
- .README/rules/require-returns-description.md
- .README/rules/require-returns-type.md
- .README/rules/require-returns.md
- README.md
- src/iterateJsdoc.js
- src/rules/implementsOnClasses.js
- src/rules/noTypes.js
- src/rules/requireParamDescription.js
- src/rules/requireParamName.js
- src/rules/requireParamType.js
- src/rules/requireReturns.js
- src/rules/requireReturnsDescription.js
- src/rules/requireReturnsType.js
- test/rules/assertions/implementsOnClasses.js
- test/rules/assertions/noTypes.js
- test/rules/assertions/requireParamDescription.js
- test/rules/assertions/requireParamName.js
- test/rules/assertions/requireParamType.js
- test/rules/assertions/requireReturns.js
- test/rules/assertions/requireReturnsDescription.js
- test/rules/assertions/requireReturnsType.js
Builds on #465
feat(`no-types`, `implements-on-classes`): add `contexts` option which if set to `any` will allow checking of virtual functions
Reuse of the `contexts` option would allow these contexts to be narrowed beyond the defaults if a project might so desire.
> Global function checking `no-types` and `implements-on-classes`

- .README/rules/require-file-overview.md
- README.md
- src/iterateJsdoc.js
- src/rules/requireFileOverview.js
- test/rules/assertions/requireFileOverview.js
feat(`require-file-overview`): allow user to specify whether checking for tag, duplicates, or preceding non-comments, and for which tags
Allows overriding of default `file` behavior (added in #464) as well as other tags like `copyright`.
> File overview `tags` option

- .README/rules/require-hyphen-before-param-description.md
- README.md
- src/rules/requireHyphenBeforeParamDescription.js
- test/rules/assertions/requireHyphenBeforeParamDescription.js
Based on top of #475.
feat(`require-hyphen-before-param-description`): add option to support checking `property`/`prop`
> Hyphens on property descs

- .README/rules/no-defaults.md
- src/index.js
- src/iterateJsdoc.js
- src/rules/noDefaults.js
- test/rules/assertions/noDefaults.js
- test/rules/index.js
feat(`no-defaults`): add new rule to reports defaults on `@param` or `@default` and optionally report optional args; fixes #477
Non-breaking as not added to "recommended".
> `no-defaults`: new rule to report defaults on `@param` or `@default` and optionally optional args

- .README/rules/no-bad-blocks.md
- src/index.js
- src/iterateJsdoc.js
- src/rules/noBadBlocks.js
- test/rules/assertions/noBadBlocks.js
- test/rules/index.js
feat(`no-bad-blocks`): add rule to check for multi-line-style comments which fail to meet criteria of a jsdoc block
Expects jsdoc block to be a multiline-style comment beginning with two asterisks.
If beginning with only one, while having whitespace followed by whitespace or asterisks, and
an at-sign (`@`) and some non-whitespace (as with a jsdoc block tag), then report.
Non-breaking, as haven't added to "recommended".
> `no-bad-blocks`: rule to check for multi-line-style comments which fail to meet criteria of jsdoc blocks

- README.md
- src/rules/checkValues.js
- test/rules/assertions/checkValues.js
`semver.valid()` requires a trimmed string: with leading or trailing whitespace, `semver.valid()`always returns `false`
> fix:`check-values` for `@version` and `@since` reported invalid version with leading/trailing whitespace

- README.md
- src/rules/requireReturnsCheck.js
- test/rules/assertions/requireReturnsCheck.js
For GCC `@record` tag marks classes/functions as a [Structural Interface](https://github.com/google/closure-compiler/wiki/Structural-Interfaces-in-Closure-Compiler) making it more or less similar to `@interface` tags. Particularly it means `@return` annotation can be present on a function that does not actually have a `return` statement
> require-returns-check: Skip Closure Structural Interfaces (@record)

- README.md
- src/iterateJsdoc.js
- src/rules/requireReturns.js
- test/rules/assertions/requireReturns.js
Implimentation for https://github.com/gajus/eslint-plugin-jsdoc/issues/503
This PR adds for the rule `jsdoc/require-returns` a new boolean option `checkGetters`, which defaults to `true`, as is the rule current behavior of the rule without the option.
When `checkGetters = false`, it allows developers to omit the `@returns` tag for `get` functions, e.g.:
```js
// jsdoc/require-returns: ["error", { checkGetters: false }]
class Foo {
/** gets bar value of zero */
get bar() {
return 0;
}
}
```
The motivation behind this option is because in regular `eslint`, the `valid-jsdoc` rule automatically ignores `get` functions, so direct porting to this plugin is now possible. This also allows for a greater flexibility as developers can choose if they do or do not want to require the `@returns` tag …
> feat(require-returns): add checkGetter option

- .README/README.md
- README.md
This fixes a mixed content issue on the npm page for this package:
It also normalizes line endings to LF, GitHub's online editor would previously say they are mixed, and then normalize them to CRLF, causing 11k lines diffs when you want to change a small thing.
> readme: Update shields.io links to HTTPS and fix mixed line endings

- README.md
- package.json
- src/bin/generateReadme.js
- src/iterateJsdoc.js
- src/rules/noTypes.js
- test/rules/assertions/noTypes.js
- test/rules/assertions/requireParam.js
Currently, the fix for `no-types` results in the removal of some asterisks from multiline descriptions. This makes `eslint-plugin-jsdoc` somewhat jarring to adopt.
The proper fix here probably requires https://github.com/syavorsky/comment-parser/pull/74.
> test(no-types): check that the fix for no-types preserves asterisks

- .README/rules/require-returns-description.md
- README.md
- src/rules/requireReturnsDescription.js
- test/rules/assertions/requireReturnsDescription.js
feat(require-returns-description): avoid reporting missing descriptions for `Promise<void>` and `Promise<undefined>`. Fixes #525.
> exempt descriptions for `Promise<void>` and `Promise<undefined>`

- .README/rules/check-param-names.md
- .README/rules/check-property-names.md
- README.md
- src/rules/checkParamNames.js
- src/rules/checkPropertyNames.js
- test/rules/assertions/checkParamNames.js
- test/rules/assertions/checkPropertyNames.js
Allows disabling duplicate fixing.
> feat(check-param-names, check-property-names): add `enableFixer` option

- src/rules/requireParam.js
- test/rules/assertions/requireParam.js
Currently builds on #531
Allows disabling of destructured checks (by setting `checkDestructured` to `false`).
Fixes #530.
> `checkDestructured` property to disable destructured checks

- .README/README.md
- README.md
- src/jsdocUtils.js
- test/rules/assertions/checkTagNames.js
> fix(check-tag-names): Workaround for 'constructor' key in tagNamePreference

- .babelrc.json
- package.json
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/checkTypes.js
- src/rules/checkValues.js
- src/rules/emptyTags.js
- src/rules/noUndefinedTypes.js
- src/rules/requireDescriptionCompleteSentence.js
- src/rules/requireJsdoc.js
- src/rules/requireParam.js
- src/rules/validTypes.js
- test/rules/assertions/checkTagNames.js
@gajus, here's how the linting changes may look...  (Related to https://github.com/gajus/eslint-config-canonical/issues/23 )
Though I re-enabled `reduce` in a couple cases, I think it is mostly more readable. (I conceptually like `reduce` better as it is just one action (e.g., not a `map` and `join`, or a variable declaration and `forEach`), but I'll admit it can *look* less intuitive, so except in the two cases, I think it has indeed become more readable after dropping `reduce`).
> chore: update dep. spdx-expression-parse and devDeps.; apply new linting

- README.md
Users and newcomers should not need to know what file to modify to properly configure the plugin.
This revision allows for no asking if this is package.json or some other file, but is in fact .eslintrc.
> More accurate Configuration section

- README.md
- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
Fixes #427.
- feat(`require-description-complete-sentence`): add `newlineBeforeCapsAssumesBadSentenceEnd` option to disable heuristic for caps after newlines being assumed to be a bad sentence end.
I might suggest further changing this to be `false` by default but it would be breaking in the sense of changing behavior for those expecting it to continue reporting.
> `require-description-complete-sentence`: `newlineBeforeCapsAssumesBadSentenceEnd` option

- .README/rules/require-hyphen-before-param-description.md
- README.md
- src/rules/requireHyphenBeforeParamDescription.js
- test/rules/assertions/requireHyphenBeforeParamDescription.js
feat(require-hyphen-before-param-description): add `tags` option for setting specific tags (or any tags) to follow rules for or against hyphen descriptions; now allows property to be set differently than param; fixes #553
`{checkProperties: true}` should be replaced by: `{tags: {'property': 'always|never'}}`
> `require-hyphen-before-param-description`: add `tags` option

- README.md
- src/rules/checkParamNames.js
- test/rules/assertions/checkParamNames.js
This PR fixes the false negatives in the check-param-names rule for the following cases:
```js
/**
* @param cfg
* @param cfg.foo
* @param cfg2
*/
function quux ({foo}, cfg2) {
}
// Results in: @param "cfg2" does not exist on cfg
/**
* @param cfg
* @param cfg.foo
* @param baz
* @param baz.cfg
*/
function quux ({foo}, {cfg}) {
}
// Results in: @param "baz.cfg" does not exist on cfg
```
> Fix bug with destructured parameters in check-param-names

- .README/rules/require-returns.md
- .README/rules/require-throws.md
- README.md
- src/index.js
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/requireThrows.js
- test/rules/assertions/requireThrows.js
- test/rules/index.js
This adds a new rule `require-throws`, that requires a `@throws` statement in the JSDoc if the function body contains the `throw` keyword.
I based this off of `require-returns`, as suggested in https://github.com/gajus/eslint-plugin-jsdoc/issues/566
> Add rule `require-throws`

- .README/README.md
- README.md
I forgot to add the `require-throws` rule to the main README. This updates the README to include all the `require-throws` documentation.
> Add require-throws to the README

- README.md
- src/jsdocUtils.js
- src/rules/checkParamNames.js
- test/rules/assertions/checkParamNames.js
feat(`check-param-names`): report missing/extraneous TypeScript annotation properties in both directions and report mismatches of parameter names which are parents to annotations; fixes #491
Also provides more precise line number reporting.
In some ways this is more of a fix, but I wanted a regular TS user to confirm that a case like:
```js
export class SomeClass {
/**
* @param prop
* @param prop.foo
* @param prop.bar
*/
constructor(options: { foo: string, bar: string }) {}
}
```
...should report a mismatch between `prop` and `options` and not just the nested items--as seems to make sense to me.
> annotation mismatches

- .README/README.md
- .babelrc.json
- .ncurc.js
- .travis.yml
- README.md
- package.json
- src/bin/generateReadme.js
- src/jsdocUtils.js
- src/rules/checkTypes.js
- src/rules/noUndefinedTypes.js
- src/rules/requireDescriptionCompleteSentence.js
- src/rules/requireJsdoc.js
- src/rules/validTypes.js
- test/rules/assertions/validTypes.js
feat(`check-types`, `no-undefined-types`, `valid-types`): use mode-aware type parsing; fixes part of #356; fixes #495
Requires Node 10+
Also:
1. Adds support for "permissive" mode
2. Checks "param" for valid namepaths
3. Updates to take advantage of cleaner Node 10+ syntax
> Mode-aware type/namepath parsing

- .README/README.md
- README.md
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/validTypes.js
- test/rules/assertions/validTypes.js
feat(`valid-types`): disallow namepath on `interface` tag for Closure mode; continue checking on jsdoc; fixes part of #356
Also avoids checking namepath on `interface` tag for `no-undefined-types` and `check-types` when in closure mode.
> `valid-types`: disallow namepath on `interface` tag for Closure

- .README/README.md
- .README/rules/check-tag-names.md
- .README/rules/valid-types.md
- README.md
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/validTypes.js
- src/tagNames.js
- test/rules/assertions/checkTagNames.js
- test/rules/assertions/validTypes.js
Builds on #587.
feat(`check-tag-names`): for "closure" mode, prefer "return" over "returns"; fixes part of #356
> Check tag names closure

- .README/README.md
- .README/rules/check-syntax.md
- README.md
- src/rules/checkSyntax.js
- test/rules/assertions/checkSyntax.js
Builds on #587 and #588.
feat(`check-syntax`): only check against Closure syntax in "jsdoc" and "typescript" mode; fixes part of #356
"jsdoc" mode or new "permissive" mode will not complain (in preparation for the rule potentially preventing other syntaxes by mode (where jsdoctypeparser does not forbid)).
> Check syntax closure

- .README/README.md
- README.md
- src/jsdocUtils.js
- test/rules/assertions/validTypes.js
Builds on #587, #588, and #589.
feat(`valid-types`, `no-undefined-types`): check `module` for namepath in non-"typescript" mode; fixes part of #356
> Module namepath

- README.md
- src/rules/requireJsdoc.js
- test/rules/assertions/requireJsdoc.js
feat(`require-jsdoc`): add `enableFixer` option; if set to `false`, will avoid fixer; fixes #372
As per discussion in #372, let me know if you want me to change this to make a break from previous behavior by instead making `enableFixer` off by default. (If so, I think `enableFixer` should be added as `true` on most existing tests so that the docs continue to make clear how/where the fix will appear.)
Also, @gajus, @golopot seems to favor [ESLint's approach](https://github.com/eslint/eslint#semantic-versioning-policy) of only treating something as breaking if it is likely to increase the number of errors. I personally favor an approach which I think is more in line with the spirit of semver by requiring a breaking change if there will be fewer errors (and there was legitimate reason to see …
> `require-jsdoc`: add `enableFixer` option

- .README/rules/require-jsdoc.md
- README.md
- src/rules/requireJsdoc.js
- test/rules/assertions/requireJsdoc.js
feat(`require-jsdoc`): add `exemptEmptyConstructors` and set `true` as default; fixes #600
If `true` will prevent empty constructors from needing documentation.
Also adds `checkConstructors`, `checkGetters`, and `checkSetters` options (default `true`) to allow the complete disabling of checks on these methods as per other require-* rules.
Is "light breaking" in that it will stop checking empty constructors, but even I don't think it really requires a breaking change.
> `require-jsdoc`: add `exemptEmptyConstructors` as default

- README.md
- package.json
- test/rules/assertions/checkTypes.js
- test/rules/assertions/validTypes.js
chore: update `jsdoctypeparser`
1. Adds spaces between union items per jsdoctypeparser update.
2. Removes JSDuck support (unions with "/" instead of "|")
Also adds support in typescript mode for `readonly` and intersections (`X & Y`)
(If someone was against the whitespace change, jsdoctypeparser could perhaps preserve whitespace and/or add an `eslint-plugin-jsdoc` fixer option to configure desired whitespace.)
> Jsdoctypeparser update

- .README/README.md
- .README/rules/check-types.md
- README.md
- src/rules/checkTypes.js
- test/rules/assertions/checkTypes.js
feat(`check-types`): allow two types (set one to the other in `preferredTypes`); make this the default for typescript with "object"/"Object"
I figure this approach is already familiar with `check-tag-names`.
(However, if preferred I could instead as as a new array option which acted as a whitelist to restore the ability to use certain default-prohibited types.)
~Also disables an eslint rule to prevent errors until we hear back on whether we can skip that, if canonical may be changed, etc.~
> `check-types`: allowing different cased types

- README.md
- src/jsdocUtils.js
- src/rules/checkParamNames.js
- test/rules/assertions/checkParamNames.js
Fixes: #598 
A key in a destructured object that is passed as a function parameter could be a string or a number. This case was previously not handled by `getParamName()`.
Example that failed before and succeeds now:
```js
const someFunction = ({ 
"value": renamedValue,  // eslint throws Unsupported function signature format.
otherArg,
}) => {
console.log("not important");
}
```
> fix: Object destructuring in function parameters if key is string

- README.md
- src/rules/requireDescription.js
- test/rules/assertions/requireDescription.js
feat(`require-description`): report more precisely the action to take when "body" `descriptionStyle` is set and where user (only) has a desc/description tag; fixes #608
> Report more precisely when `descriptionStyle: 'body'` and only `@desc`/`@description` present

- .README/README.md
- .README/rules/check-types.md
- .README/rules/no-undefined-types.md
- .README/rules/valid-types.md
- README.md
- src/getDefaultTagStructureForMode.js
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/requireJsdoc.js
- src/rules/validTypes.js
- test/eslint/getJSDocComment.js
- test/rules/assertions/checkParamNames.js
- test/rules/assertions/checkTypes.js
- test/rules/assertions/noBadBlocks.js
- test/rules/assertions/noUndefinedTypes.js
- test/rules/assertions/requireJsdoc.js
- test/rules/assertions/validTypes.js
feat(`check-types`, `no-undefined-types`, `valid-types`): Add `structuredTags` setting to control whether the type and namepath portions should be checked for validity and whether such portions are required, and to let user-defined "namepath-defining" tags be added to defined types. Closes #481
Drops `checkSeesForNamepaths` setting. Use `{settings: {jsdoc: {structuredTags: {name: 'namepath', type: false, required: ['name'],}}}}` instead.
Also:
1. Clarifies in more cases where a problem is specific to the mode or not
2. Reports simultaneous invalid name *and* type errors
3. `typdef` now requires `allowEmptyNamepaths: false,` to report empty names (as with other tags)
4. Requires a name for `event` and `external` (and `extends` in jsdoc mode); some tweaking of other tags …
> feat: `structuredTags` setting to control type/name portions of existing or custom tags

- .README/rules/check-param-names.md
- .README/rules/require-param.md
- README.md
- src/rules/checkParamNames.js
- test/rules/assertions/checkParamNames.js
feat(`check-param-names`): add `checkDestructured` option to allow disabling of destructured checking; fixes part of #616
Also improves display of errors when destructured properties are present
> `check-param-names`: add `checkDestructured` option

- .README/rules/require-param.md
- README.md
- src/rules/requireParam.js
- test/rules/assertions/requireParam.js
feat(`require-param`): add `checkDestructuredRoots` option; fixes #616
> feat(`require-param`): add `checkDestructuredRoots` option; fixes #616

- src/rules/checkExamples.js
Examples inside JSDoc comments cant comply with the `jsdoc/require-jsdoc` rule, because the closing comment of the nested JSDoc would close the multiline comment that contains the example.
> fix(`check-examples`): disable jsdoc/require-jsdoc

- .README/README.md
- .README/rules/no-bad-blocks.md
- README.md
- src/rules/noBadBlocks.js
- test/rules/assertions/noBadBlocks.js
This allows TypeScript directive comments in block comments.
Although these comments are mostly written using line comments, block comments must be used in some situations, e.g. when inside JSX tags.
> fix(`no-bad-blocks`): allow TypeScript directive comments

- .README/rules/check-types.md
- README.md
It was a bad typo since the whole rule is about checking case.
> Fixed typo in check-types.md

- README.md
- src/rules/checkParamNames.js
- src/rules/requireParam.js
- test/rules/assertions/checkParamNames.js
- test/rules/assertions/requireParam.js
fixes [#569]([https://github.com/gajus/eslint-plugin-jsdoc/issues/569](https://github.com/gajus/eslint-plugin-jsdoc/issues/569))
Check the type of destructured parameters in the require-param rule.
> fix(`require-param`): check deeply destructured parameters (fixes #569)

- .README/rules/require-example.md
- README.md
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/requireExample.js
- test/rules/assertions/requireExample.js
> feat(`require-example`): add `exemptNoArguments` option

- .README/rules/check-lines-alignment.md
- src/index.js
- src/rules/checkLinesAlignment.js
- test/rules/assertions/checkLinesAlignment.js
- test/rules/index.js
When developing for WordPress, there is a [recommended standard](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/javascript/#aligning-comments) to have the comment lines aligned.
Some days ago, we created an Eslint rule for that: https://github.com/Automattic/eslint-plugin-jsdoc-alignment/
It was created with the purpose to start using it and soon submit a contribution to add it to the `eslint-plugin-jsdoc`, which makes much more sense.
If this PR is approved, the current `eslint-plugin-jsdoc-alignment` will be deprecated in favor of this rule.
It's my first contribution to `eslint-plugin-jsdoc`, so I'm sorry if I missed something. But I'll be happy to fix anything if needed.
❌ Incorrect example:
```js
/**
* Function description.
*
* @param {string} …
```
> Add lines alignment rule

- .README/README.md
- .README/rules/empty-tags.md
- README.md
- src/iterateJsdoc.js
- src/rules/emptyTags.js
- test/rules/assertions/emptyTags.js
- test/rules/assertions/requireParam.js
feat: add `ignoreInternal` setting to ignore blocks with `@internal` tags; fixes #639
Not applied to `empty-tags` rule (which now also enforces an empty `@internal`)
> feat: Add `ignoreInternal` setting

- README.md
- src/exportParser.js
- test/rules/assertions/requireJsdoc.js
As discussed in #640, adding support for Typescript interfaces
> fix(`require-jsdoc`): support `TSInterfaceDeclaration` with `publicOnly`

- .README/rules/check-examples.md
- .README/rules/check-line-alignment.md
- .README/rules/check-param-names.md
- .README/rules/check-property-names.md
- .README/rules/empty-tags.md
- .README/rules/require-property-description.md
- .README/rules/require-property-name.md
- .README/rules/require-property-type.md
- README.md
- src/rules/checkExamples.js
- test/rules/assertions/checkExamples.js
feat(`check-examples`): add options `checkDefaults`, `checkParams`, `checkProperties`; fixes #473
This PR allows `check-examples` to also check the value of `@default`/`@defaultvalue` tags (which can include code subject to linting) as well as the default values of optional `@param` or `@property` tags.
Also adds `matchingFileNameDefaults`, `matchingFileNameParams`, and `matchingFileNameProperties` to simulate a file name which can cause content within these tags to be linted differently from `@example` (by use of `overrides`).
> `check-examples`: add options to allow checking `@default` values and `@param`/`@property` defaults

- .README/README.md
- .README/rules/require-yields.md
- README.md
- src/index.js
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/requireYields.js
- test/rules/assertions/requireYields.js
- test/rules/index.js
- feat(`require-yields`): add new rule to check that `yield` has documentation; for #354
- feat(`require-yields`): add options to check that `next` has documentation
Note that Gajus approved the rule concept in the referenced issue.
(Btw, your earlier refactoring on `hasReturnValue`, @golopot , also helped inspire a more minimal version of what was needed for `hasYieldValue`.)
> Require yields

- .README/README.md
- .README/rules/require-yields-check.md
- .README/rules/require-yields.md
- README.md
- src/index.js
- src/rules/requireYieldsCheck.js
- test/rules/assertions/requireYieldsCheck.js
- test/rules/index.js
Builds on #674.
- feat(`require-yields-check`): add rule to check that `yield` (of proper form) is present in the function body; fixes #354
- docs(`require-yields`): remove info intended for `require-yields-check`
> Require yields check

- .README/rules/check-param-names.md
- .README/rules/require-param.md
- README.md
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/checkParamNames.js
- src/rules/requireParam.js
- test/rules/assertions/checkParamNames.js
- test/rules/assertions/requireParam.js
fix(`require-param`, `check-param-names`): add option `useDefaultObjectProperties` for expecting documentation or avoiding reporting of documented; addresses part of #676
> `require-param` and `check-param-names`: `useDefaultObjectProperties` option

- .README/rules/check-param-names.md
- README.md
- src/rules/checkParamNames.js
- test/rules/assertions/checkParamNames.js
Builds on #678. Closes #676.
- feat(`check-param-names`): add options `disableExtraPropertyReporting` to allow extra properties to be documented without error (as long as there are no siblings destructured as for such cases, they will still be expected since the function is not using them)
There may be cases where a project would want to document even these, but they can do so by using a separate `typedef`, so I'm not sure there's need for an additional boolean to handle that case.
> Disable extra property reporting

- .README/rules/check-line-alignment.md
- README.md
- src/rules/checkLineAlignment.js
- test/rules/assertions/checkLineAlignment.js
feat(`check-line-alignment`): allow `tags` option to configure which tags should be aligned.
We also allow other tags to be detected which might not have a name portion (and thus need special handling)
Addresses this [comment](https://github.com/gajus/eslint-plugin-jsdoc/issues/680#issuecomment-766488802).
> feat(`check-line-alignment`): `tags` option

- .README/rules/require-returns.md
- README.md
- src/bin/generateReadme.js
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/noUndefinedTypes.js
- src/rules/requireDescriptionCompleteSentence.js
- src/rules/requireReturns.js
- test/rules/assertions/requireReturns.js
- test/rules/assertions/requireThrows.js
- test/rules/assertions/requireYields.js
- test/rules/index.js
feat(`require-returns`): if function returns a Promise whose executor resolves with undefined, avoid need to document unless `forceReturnsWithAsync` is set; fixes #550
Note that if this is merged, #682 will need to add mention that our `resolve` detection is not fully complete either, since there are more edge cases where this PR does not check. But I expect it is a good beginning.
> `require-returns`: check for `Promise` executor

- README.md
- src/rules/checkLineAlignment.js
- test/rules/assertions/checkLineAlignment.js
Fixes #680
This PR is a refactor for the alignment rule when using the option `always` to use the comment-parser.
> Update line alignment rule to align any tag

- README.md
- src/exportParser.js
- test/rules/assertions/requireJsdoc.js
In typescript, when interface is export, property and method is also exposed. but unlike class method and property, they are not retrievable from AST, so they failed on both esm and AST check of public, in this PR I fix this issue.
more detail can be find in tests
> Fix typescript interface working with `publicOnly` options

- .README/rules/require-jsdoc.md
- README.md
- src/jsdocUtils.js
- src/rules/requireJsdoc.js
- test/rules/assertions/requireJsdoc.js
- feat(`require-jsdoc`): allow checking for getter or setter only; fixes #515
Although I know normally @gajus and @golopot did not favor options whose schemas allowed different types, given that `checkGetters`/`checkSetters` has been around as a boolean for a while, and adding a separate `checkGettersWithSettesr`/`checkSettersWithGetters` boolean option could become a confusing headache, this PR does allow a string value for `checkGetters`/`checkSetters`.
> Options for checking getter or setter only

- .README/README.md
- .README/rules/check-types.md
- .README/rules/no-undefined-types.md
- README.md
- src/rules/checkTypes.js
- src/rules/noUndefinedTypes.js
- test/rules/assertions/checkTypes.js
- test/rules/assertions/noUndefinedTypes.js
- feat(`check-types`): check `settings.jsdoc.structuredTags` for an array of permissible types, reporting if not present; fixes #695
- feat(`no-undefined-types`): allow `structuredTags` types to be auto-defined
This does not completely replace the `exemptTagContexts` option since `settings.jsdoc.structuredTags` does not provide a way to permit even invalid types.
I've included two features as they both tie in to `structuredTags` settings.
> feat(`check-types`): check `settings.jsdoc.structuredTags` for an array of permissible types

- .README/rules/check-tag-names.md
- README.md
- src/rules/checkTagNames.js
- src/tagNames.js
- test/rules/assertions/checkTagNames.js
These tags may be used to tweak how JSX is converted by Babel or TypeScript.
See https://babeljs.io/docs/en/babel-plugin-transform-react-jsx
> Allow the use of jsx annotations

- .README/README.md
- .README/rules/require-asterisk-prefix.md
- README.md
- src/index.js
- src/iterateJsdoc.js
- src/rules/requireAsteriskPrefix.js
- test/rules/assertions/requireAsteriskPrefix.js
- test/rules/index.js
This rule checks that each line of the jsdoc comment starts with an asterisk. For composability with
other rules, this does not check the alignment or indentation of the comment content.
Fixes #199
> feat: add require-asterisk-prefix rule

- README.md
- src/alignTransform.js
- src/rules/checkLineAlignment.js
- test/rules/assertions/checkLineAlignment.js
Part of #680
Close #689
This PR adds support to the `tags` option when using the `always` option.
The first PR for this feature was the https://github.com/gajus/eslint-plugin-jsdoc/pull/689, but the approach wasn't being enough, needing a lot of hacks. So I changed the approach, creating a new transform based on the original `align`, but adding support to custom tags.
It still reports the errors for the entire block, different than what was suggested in https://github.com/gajus/eslint-plugin-jsdoc/issues/680#issuecomment-770314024.
Another idea for a new feature in the future:
- We could add a new option to force the alignment similar to the `never` for the tags that aren't in the `tags` when using the `always`.
> Add line alignment tags support when using `always`

- .babelrc.json
- .travis.yml
- package.json
- src/jsdocUtils.js
Also:
- Build: Switch to Node 12 target
- Linting: Use `flat` API
- Travis: Add Node 16, remove Node 10
- npm: Update devDep.
> chore: require engines Node 12+

- src/alignTransform.js
- src/rules/checkLineAlignment.js
- test/rules/assertions/checkLineAlignment.js
This introduces the new option `preserveMainDescriptionPostDelimiter ` for the `check-line-alignment` rule.
This new option will preserve the post delimiter (spacings after the `*`) in the main description when using the `always` option.
```js
/**
* Function description
*           description with post delimiter.
*
* @param {string} lorem Description.
* @param {int}    sit   Description multi words.
*/
```
Notice that it just applies to `always` because the `never` always preserves the spacing. I thought about doing it as default to `always` too, but since we already released it in that way, I added a new option to avoid breaking changes.
> Add `preserveMainDescriptionPostDelimiter` option to `check-line-alignment` rule

- .README/rules/no-bad-blocks.md
- README.md
- src/rules/noBadBlocks.js
- test/rules/assertions/noBadBlocks.js
feat(`no-bad-blocks`): add `preventAllMultiasteriskBlocks` boolean option to allow reporting of any multi-asterisked multiline comments
> `no-bad-blocks`: add `preventAllMultiasteriskBlocks`  option

- .README/README.md
- .README/rules/tag-lines.md
- README.md
- src/index.js
- src/iterateJsdoc.js
- src/rules/tagLines.js
- test/rules/assertions/tagLines.js
- test/rules/ruleNames.json
Includes a `always` vs. `never` option as well as two special options for `always` (`count` and `noEndLine`). Fixes #93.
> feat: new rule `tag-line`; fixes #93

- .README/README.md
- .README/rules/multiline-blocks.md
- README.md
- src/index.js
- src/iterateJsdoc.js
- src/rules/multilineBlocks.js
- test/rules/assertions/multilineBlocks.js
- test/rules/ruleNames.json
Should fix the last of #199 whenever ~#727, #728, and~ #730 may be merged.
~Builds on #727. You can review the diffs now or I can wait to rebase whenever that may be merged.~
feat(`multiline-blocks`): allow control of how and whether jsdoc blocks can be expressed as single or multiple line blocks
> Multiline blocks

- .README/README.md
- .README/rules/no-multi-asterisks.md
- README.md
- src/index.js
- src/rules/noMultiAsterisks.js
- test/rules/assertions/noMultiAsterisks.js
- test/rules/ruleNames.json
feat: `no-multi-asterisks` rule to prevent multiple asterisks with middle delimiters or at end of blocks
Fixes #199 (other fixes have now been merged).
> `no-multi-asterisks` rule

- .README/rules/check-line-alignment.md
- README.md
- src/alignTransform.js
- src/rules/checkLineAlignment.js
- test/rules/assertions/checkLineAlignment.js
Fixes #732
It introduces the `customSpacings` option to the line alignment rule. You can use something like:
```js
customSpacings: {
postDelimiter: 2,
postTag: 3,
postType: 2,
},
```
If the spacing is not defined, it uses `1` by default.
> Add custom spacing to line alignment rule

- .README/rules/multiline-blocks.md
- README.md
- src/rules/multilineBlocks.js
- test/rules/assertions/multilineBlocks.js
- test/rules/assertions/noMultiAsterisks.js
feat(`multiline-blocks`): add `noFinalLineText` option; fixes #738
> feat(`multiline-blocks`): add `noFinalLineText` option

- .README/rules/tag-lines.md
- README.md
- src/rules/tagLines.js
- test/rules/assertions/tagLines.js
feat(`tag-lines`): add `tags` option to override behavior on a tag-specific basis (including only applying to tag(s)); fixes #734
> `tag-lines`: add `tags` option

- .README/README.md
- .README/rules/match-name.md
- README.md
- src/index.js
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/matchName.js
- test/rules/assertions/matchName.js
- test/rules/ruleNames.json
Allows reporting and in some cases fixing portions of the name (e.g., `@tag name`, based on context or the presence of other tags.
> feat: `match-name` rule; fixes #509

- src/rules/validTypes.js
- test/rules/assertions/validTypes.js
This parses name paths in permissive mode. It might be better that `jsdoc-type-pratt-parser` allows a specific name path parsing mode or name parsing mode so this can only be a name path or a type in the specified mode.
This is somewhat more permissive than before but fixes the false positives. This now allows all names of tags that are scanned for namepaths to also be in jsdoc mode.
I will introduce the name parsing mode in `jsdoc-type-pratt-parser` but it will take some time (weeks) as I do not have very much free time at hands at the moment.
Fixes #750
> fix(valid-types): parse name paths as permissive.

- .README/rules/match-description.md
- README.md
- src/rules/matchDescription.js
- test/rules/assertions/matchDescription.js
- feat: `message` options for `match-description`; fixes #688
Provide a custom message for errors.
> feat: `message` options for `match-description`; fixes #688

- README.md
- package.json
- src/alignTransform.js
- test/rules/assertions/checkLineAlignment.js
Fixes #745.
Waiting on feedback on https://github.com/syavorsky/comment-parser/pull/132 (and possibly to use a stable update to `comment-parser` if also ready).
@renatho : You might want to see my [comment](https://github.com/syavorsky/comment-parser/pull/132#issuecomment-876814403) there. In particular, if the `delim`-setting code is unreachable, then I imagine we don't really need to expand on this line:
```js
tokens.postDelimiter = nothingAfter.delim ? '' : space(spacings.postDelimiter);
```
to this:
```js
tokens.postDelimiter = nothingAfter.delim ? (tokens.postDelimiter === '\r' ? '\r' : '') : space(spacings.postDelimiter);
```
> fix(`check-line-alignment`): preserve carriage returns; fixes #745

- .README/rules/require-returns-check.md
- README.md
- src/rules/requireReturnsCheck.js
- test/rules/assertions/requireReturnsCheck.js
- feat(`require-returns-check`): add `exemptGenerators` option (default on for typescript mode) to allow `@returns` to be present even without `return`
> `require-returns-check`: Add `exemptGenerators` option

- src/rules/tagLines.js
The current schema of `tag-lines` for the property tags is incorrect as `patternProperties` is inside `properties` instead of only `patternProperties`.
As such only `tags.patternProperties` is checked and not as wanted `tags.*`.
> [tag-lines] Schema fix for tags

- .README/README.md
- .README/rules/require-description.md
- .README/rules/require-example.md
- .README/rules/require-param.md
- .README/rules/require-returns.md
- .README/rules/require-throws.md
- .README/rules/require-yields.md
- README.md
- src/iterateJsdoc.js
- test/rules/assertions/requireParam.js
This will allow `@ignore` to avoid the need for accompanying documentation by default (unless a new setting, `ignoreReplacesDocs` is set to `false`).
> feat: add `ignoreReplacesDocs` setting (defaulting to true); fixes #780

- README.md
- src/rules/checkIndentation.js
- test/rules/assertions/checkIndentation.js
feat(`check-indentation`): ensure masking through decorators within tags (fixes #789)
> feat(`check-indentation`): ensure masking through decorators within tags

- README.md
- src/rules/requireReturnsCheck.js
- src/rules/requireThrows.js
- src/rules/requireYieldsCheck.js
- test/rules/assertions/requireReturnsCheck.js
- test/rules/assertions/requireThrows.js
- test/rules/assertions/requireYieldsCheck.js
feat(`require-returns-check`, `require-yields-check`, `require-throws`): confirm that a "never" value is indeed present
Inspired by and closes #817 .
Note that as we have no `require-throws-check` (which would be pretty useless since functions often call other functions that throw without having a throw statement themselves), I've added the "never" checking to `require-throws`.
> confirm that a "never" value is indeed present

- .README/rules/check-types.md
- README.md
- src/rules/checkTypes.js
- test/rules/assertions/checkTypes.js
fix(`check-types`): prevent parent objects from being reported in "typescript" mode even with generic preferredTypes match (unless there is `unifyParentAndChildTypeChecks` config); fixes #800
> fix(`check-types`): prevent parent objects from being reported in "typescript" mode

- .README/README.md
- .README/rules/sort-tags.md
- README.md
- src/defaultTagOrder.js
- src/index.js
- src/iterateJsdoc.js
- src/rules/sortTags.js
- test/rules/assertions/sortTags.js
- test/rules/ruleNames.json
Welcome to give feedback on:
To-dos:
Although it might be nice in some ways to try to promote a pseudo-standard in adding this rule to `recommended`, I figure it may be too annoying, especially for those who don't use `--fix` to have to remember the complex sorting algorithm.
- feat: add `sort-tags` rule
> feat: add `sort-tags` rule

- .README/rules/check-values.md
- README.md
- package.json
- src/rules/checkValues.js
- test/rules/assertions/checkValues.js
feat(`check-values`): add checking of `kind`
Also, updates `jsdoccomment` and devDeps.
> feat(`check-values`): add checking of `kind`

- .travis.yml
- CONTRIBUTING.md
- package.json
Cleans up the scripts so all the CLI arguments are in the config sections in package.json. This allows the CLI to be overloaded while calling the scripts if needed.
Also allows IDEs to hook into with the debugger, since the config is loaded by Mocha.
> test: move Mocha and NYC config from CLI

- .README/rules/match-description.md
- .README/rules/tag-lines.md
- README.md
- src/rules/matchDescription.js
- src/rules/tagLines.js
- test/rules/assertions/matchDescription.js
- test/rules/assertions/tagLines.js
- feat(`tag-lines`): add `dropEndLines` option; fixes #847
- fix(`match-description`): adjust default to allow for trailing whitespace but do check for such WS now
Regular expressions now need to take account for trailing whitespace
I've put these two together as they both related to allowing for trimming trailing lines
> feat(`tag-lines`): add `dropEndLines` option; fixes #847

- src/iterateJsdoc.js
Benchmark on the [ESLint project](https://github.com/eslint/eslint) with `time npx eslint .` (real time) :
|  | before | after |
| --- | -- | -- |
| run 1 | 47.7s | 31.0s |
| run 2 | 47.8s | 31.2s |
| run 3 | 48.7s | 31.2s |
> perf: improve performance for rules

- .README/rules/check-types.md
- README.md
- src/rules/checkTypes.js
- test/rules/assertions/checkTypes.js
feat: unless the user supplies their own `object` type `preferredTypes`, prefer `object` for plain objects and otherwise prefer `Object<>`; fixes #800
I'm not yet convinced we're ready for #834 , but in anticipation of a likely future change, I think we should go ahead and enforce the best compatibility with TypeScript now even for plain jsdoc users.
Now admittedly, TypeScript has an issue to change things to [support equivalent behavior for either form](https://github.com/microsoft/TypeScript/issues/20555) when within JSDoc, but regardless, it seems that it is better for us to enforce operating in a manner closer to how TypeScript is to behave (that `Object` is discouraged in plain form and `object` is the more basic type allowing for `Object.create(null)) and how it makes sense to …
> Prefer TypeScript compatibility

- .travis.yml
- package.json
- src/rules/requireDescriptionCompleteSentence.js
We currently have three seperate security advisories for this package due to the sub packages of regextras. I noticed that there is only one use of the regextras package and it could be replaced with only a few lines and would signifigantly reduce the size of the package and the impact of the downstream dependencies.
> removed regextra library to reduce dependencies

- .README/README.md
- .README/rules/require-example.md
- CONTRIBUTING.md
- README.md
- src/rules/requireExample.js
- test/rules/assertions/requireExample.js
Currently there is no way to disable the fixer for `require-example`. This adds that option following the pattern from other rules.
- Add test coverage for option
- Add option to rule
- Wrap fixer logic in a conditional
> fix: add `enableFixer` option to `require-example`

- .babelrc.json
I think this is more of a fix in some ways, and really part of the intent of requiring Node 14 in 39.0.0, but thought I'd submit here, if nothing else than to confirm that it works on our test environments.
> feat: target Node 14 in builds now that using it

- .README/README.md
- .README/rules/require-jsdoc.md
- README.md
- src/jsdocUtils.js
- src/rules/requireJsdoc.js
- test/rules/assertions/requireJsdoc.js
feat(`require-jsdoc`): add `minLineCount` option (including on `contexts`) to avoid reporting short functions/contexts; fixes #870
> `minLineCount` option to avoid reporting short functions/contexts

- README.md
- src/iterateJsdoc.js
- test/rules/assertions/requireParamType.js
Hello, I've been dealing with an annoying bug using NeoVim + LSP + eslint. If I'm typing a function parameter from scratch, like `/** @param {nu`, this plugin rightfully reports an error (`require-param-type`) since I haven't finished typing the type.
But it reports column number = 0 which causes NeoVim's LSP client to crash, interrupting my typing.
Presumably it would be impossible to error on an empty line, so I'm hoping adding column = 1 when the upstream parser doesn't report a column number is okay as a quick fix. I'm sure there is a better way to get the real column number but I don't have time to dig any deeper right now.
Not sure if other rules are affected or not, this is the only one I ran into.
Thanks!
---
`x.js`
```js
/**
* @param {a xxx
*/
```
`yarn eslint x.js` before commit …
> fix(`require-param-type`): report column=1

- .travis.yml
- package.json
Node 18 is out. This adds it to the CI and package.json.
Node 18 requires newer versions of GLIBC which are included in Ubuntu 20.04 LTS (focal), but not Ubuntu 16.04 LTS (xenial)
Relates to https://github.com/es-joy/jsdoccomment/pull/7
> build: add Node 18 support

- CONTRIBUTING.md
Minor cleanup to improve conciseness as well as fix a few spelling and grammar issues
> docs(contributing): spelling and grammar fixes

- .npmignore
Other development related files are removed before publishing, so this can probably go also.
> build(.npmignore): add `CONTRIBUTING.md`

- README.md
- src/jsdocUtils.js
- test/jsdocUtils.js
- test/rules/assertions/checkTagNames.js
This makes it so the `check-tag-names` rule works when JSDoc tag names match `Object.prototype` properties (like `@constructor`).
Fixes #898.
> fix(`check-tag-names`): work with the constructor tag

- README.md
- src/utils/hasReturnValue.js
- test/rules/assertions/requireReturns.js
- test/rules/assertions/requireReturnsCheck.js
fix(require-returns, require-returns-check): treat non-void `TSDeclareFunction` type annotations as having a return value; fixes part of #903
> treat non-void `TSDeclareFunction` type annotations as having a return value

- .README/rules/require-param-description.md
- .README/rules/require-param-type.md
- README.md
- src/iterateJsdoc.js
- src/rules/requireParamDescription.js
- src/rules/requireParamType.js
- test/rules/assertions/requireParamDescription.js
- test/rules/assertions/requireParamType.js
feat(`require-param-type`, `require-param-description`): add `exemptDestructuredRootsFromChecks` setting; fixes #752
Also:
- feat(`require-param-type`): add `setDefaultDestructuredRootType` and `defaultDestructuredRootType` options
- feat(`require-param-description`): add `setDefaultDestructuredRootDescription` and `defaultDestructuredRootDescription` options
> Add `exemptDestructuredRootsFromChecks` setting

- .README/README.md
- README.md
- src/rules/checkTypes.js
- test/rules/assertions/checkTypes.js
feat(`check-types`): add `skipRootChecking` option to `preferredTypes` setting; fixes #863
> Skip root checking

- .husky/post-checkout
- .husky/post-commit
- .husky/post-merge
- .husky/post-rewrite
- .husky/pre-commit
- .husky/pre-push
v8.0.0 of Husky fixed shell path and args for newly created git hooks, but doesn't update existing ones, so have done that here.
See https://github.com/typicode/husky/pull/1051 and https://github.com/typicode/husky/pull/1132
> chore(.husky): shell path and arg updates

- README.md
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/requireReturnsCheck.js
- src/rules/requireYieldsCheck.js
- test/jsdocUtils.js
- test/rules/assertions/requireReturnsCheck.js
fix(`require-returns-check`, `require-yields-check`); allow `*` and `any` types to avoid reporting of missing return; fixes #950
> allow `*` and `any` types to avoid reporting of missing return

- README.md
- src/rules/requireReturnsCheck.js
- test/rules/assertions/requireReturnsCheck.js
fixes #949
Users can still rely on `require-returns-type` to catch missing types
> fix: if return type is missing, only check one path

- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
This fixes https://github.com/gajus/eslint-plugin-jsdoc/issues/779. 
The previous implementation was matching an empty line following the paragraph and performing a regex replacement on it. Added an extra test to verify the fix.
> fix: complete sentence period placement

- README.md
- test/rules/assertions/noRestrictedSyntax.js
> docs(`no-restricted-syntax`): example to limit types on @type

- README.md
- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
> fix(`require-complete-description-sentence`): allow triple backticks to end "sentence" and protect backtick content

- README.md
- test/rules/assertions/noRestrictedSyntax.js
> docs(`no-restricted-syntax`): demo erring without returns on contexts with non-void return-type type annotations

- .README/rules/check-line-alignment.md
- README.md
- src/alignTransform.js
- src/rules/checkLineAlignment.js
- test/rules/assertions/checkLineAlignment.js
> feat: `postHyphens` option to control spacing after hyphens

- .README/README.md
- README.md
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/noMissingSyntax.js
- src/rules/noRestrictedSyntax.js
- src/rules/requireJsdoc.js
- test/rules/assertions/noMissingSyntax.js
- test/rules/assertions/noRestrictedSyntax.js
- test/rules/assertions/requireDescription.js
- test/rules/assertions/requireJsdoc.js
fixes #857
Also:
- fix(`no-missing-syntax`, `no-restricted-syntax`): error message (`context` -> `contexts`)
> feat: allow `contexts` (except for `no-restricted-syntax`) to draw from global settings

- README.md
- src/rules/checkLineAlignment.js
- test/rules/assertions/checkLineAlignment.js
> fix(`check-line-alignment`): avoid adding whitespace if hyphen at end of line

- src/index.js
Fixes #997.
Explicitly disables the core ruleset rules that don't make sense for TypeScript, as some users enable those in their ESLint config for all files and then add in TypeScript rulesets as `overrides`.
> feat: add recommended-typescript, recommended-typescript-error rulesets

- .README/rules/check-types.md
- README.md
- src/rules/checkTypes.js
- test/rules/assertions/checkTypes.js
fixes #1001
For typescript mode, one must use object shorthand or index signatures, e.g., `{[key: string]: number}` or `{a: string, b: number}`
> fix: for "typescript" mode, require object shorthand or index signatures

- .README/README.md
- .README/rules/informative-docs.md
- README.md
- package-lock.json
- package.json
- src/index.js
- src/rules/informativeDocs.js
- test/rules/assertions/informativeDocs.js
- test/rules/ruleNames.json
Adds a new `informative-docs` rule with logic similar to the old `tslint-microsoft-contrib` rule (https://github.com/microsoft/tslint-microsoft-contrib/pull/555). Each JSDoc comment's description & individual tags must contain at least one new word not already in the described item.
> feat: added informative-docs rule

- README.md
- src/rules/tagLines.js
- test/rules/assertions/tagLines.js
> fix(`tag-lines`): avoid new `startLines` option expecting whitespace when no tags are present

- README.md
- src/rules/informativeDocs.js
- test/rules/assertions/informativeDocs.js
Right now, `informative-docs` isn't trimming the text it passes to `are-docs-informative`. The `Boolean(text)` check that's supposed to filter out blank text isn't accounting for whitespace. That means when there's a tag like `@class`, it calls the equivalent of:
```js
areDocsInformative('\n', 'MyAmazingThing')
```
...which is false.
This `.trim()`s the text so that whitespace is ignored.
Fixes #1039.
> fix(informative-docs): trim description text

- docs/rules/check-tag-names.md
- docs/rules/check-types.md
- docs/rules/no-undefined-types.md
- docs/rules/valid-types.md
- src/iterateJsdoc.js
- test/rules/assertions/checkTagNames.js
- test/rules/assertions/checkTypes.js
- test/rules/assertions/noUndefinedTypes.js
- test/rules/assertions/validTypes.js
Users must now opt into adding `settings.jsdoc.mode` set to `"jsdoc"` if they want normal JSDoc mode. Note that "typescript" mode does not need to imply use of TypeScript syntax, but rather use of the TypeScript flavor within JSDoc comment blocks which holds the advantages of working in IDEs to draw in third-party module documentation and optionally allowing one to type check one's JavaScript code by TypeScript. There are also tools for building docs with this flavor (e.g., typedoc).
> refactor: switch default `mode` to `typescript`; fixes #834

- docs/rules/valid-types.md
- src/rules/validTypes.js
- test/rules/assertions/validTypes.js
fixes https://github.com/jsdoc-type-pratt-parser/jsdoc-type-pratt-parser/issues/62
> fix(`valid-types`): report postfix nullable in object or labeled tuple position

- docs/rules/no-undefined-types.md
- src/getDefaultTagStructureForMode.js
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/noUndefinedTypes.js
- test/rules/assertions/noUndefinedTypes.js
While it doesn't add a new / separate rule like https://github.com/gajus/eslint-plugin-jsdoc/pull/1058 aims to, this does solve the underlying need communicated in https://github.com/gajus/eslint-plugin-jsdoc/issues/858 by updating the `no-undefined-types` rule to incorporate the [recently added feature from jsdoccomment](https://github.com/es-joy/jsdoccomment/pull/12) of parsing inline tags. Since it already marks types from other tags as used, this seem like a valuable addition until this is refactored into a separate rule or setting on `no-undefined-types`.
> feat(`no-undefined-types`): checking inline tags

- src/getDefaultTagStructureForMode.js
> fix(`no-undefined-types`): treat `@alias` as namepath-defining

- docs/rules/check-tag-names.md
- src/rules/checkTagNames.js
- test/rules/assertions/checkTagNames.js
This fixes #1085 by:
1. Removing the `module` tag from the set of `typedTagsUnnecessaryOutsideDeclare`, since typedoc promotes this, even outside declarations: See https://typedoc.org/tags/module/ 
2. Adding an early return in the check-tag-names rule's `tagIsRedundantWhenTyped` function, to avoid crashing when encountering a comment, which is not associated with an AST node.
> fix: check-tag-names crash on module comment

- docs/rules/check-line-alignment.md
- docs/rules/require-param.md
- src/alignTransform.js
- src/rules/checkLineAlignment.js
- test/rules/assertions/checkLineAlignment.js
- test/rules/assertions/requireParam.js
fix(`check-line-alignment`): only treat hyphen as separator if followed by whitespace; fixes #1091
> Line alignment hyphens

- src/rules/informativeDocs.js
- src/rules/requireAsteriskPrefix.js
> fix(`informative-docs`, `require-asterisk-prefix`): add missing and update out-of-date doc URL

- .releaserc
> chore: include release-notes-generator for Markdown in release notes

- .README/README.md
- README.md
- src/index.js
This should only impact users of typescript configs. TS should itself handle
checking for undefined types, so the (imperfect) rule has been disabled for
such users.
- feat: for typescript configs, disable `no-undefined-types`; fixes #888
- feat: add recommended-typescript-flavor configs
> no-undefined-types and TypeScript

- .README/rules/imports-as-dependencies.md
- docs/rules/imports-as-dependencies.md
- src/index.js
- src/rules/importsAsDependencies.js
- test/rules/assertions/checkExamples.js
- test/rules/assertions/importsAsDependencies.js
- test/rules/index.js
- test/rules/ruleNames.json
- tsconfig.json
> feat(`imports-as-dependencies`): add new rule to detect missing dependencies for import statements

- src/rules/importsAsDependencies.js
- test/rules/assertions/importsAsDependencies.js
> fix(`imports-as-dependencies`): don't report TypeScript proper

- src/rules/importsAsDependencies.js
> fix(`imports-as-dependencies`): catch `typings` as possible publishing source

- .README/rules/imports-as-dependencies.md
- docs/rules/imports-as-dependencies.md
- src/bin/generateRule.js
- src/rules/importsAsDependencies.js
- test/rules/assertions/importsAsDependencies.js
Also:
- fix: generation of failing/passing examples
> fix(`imports-as-dependencies`): allow relative paths

- src/rules/importsAsDependencies.js
> fix(`imports-as-dependencies`): do not log missing package.json when rule is not active

- .README/rules/match-description.md
- .README/rules/require-description.md
- docs/rules/match-description.md
- docs/rules/match-name.md
- docs/rules/no-restricted-syntax.md
- docs/rules/require-description.md
- src/getDefaultTagStructureForMode.js
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/matchDescription.js
- test/rules/assertions/matchDescription.js
- test/rules/assertions/matchName.js
- test/rules/assertions/noRestrictedSyntax.js
- feat(match-description): ensure `@desc` checked by default; check more desc-like tags by default; check non-empty tags; #233
Also:
- fix: make name required on `@template` for non-JSDoc modes
- docs(no-restricted-syntax): require access modifiers example
- docs(require-description): clarify
- test: demo checking for empty name
> feat(match-description): ensure `@desc` checked by default; check more desc-like tags by default; check non-empty tags

- docs/rules/valid-types.md
- src/jsdocUtils.js
- src/rules/validTypes.js
- test/rules/assertions/validTypes.js
- tsconfig.json
> feat(`valid-types`): check `link` and `tutorial` for content

- docs/rules/require-jsdoc.md
- src/exportParser.js
- test/rules/assertions/requireJsdoc.js
> fix(`require-jsdoc`): do not report `PropertyDefinition`'s with non-public `accessibility`

- docs/rules/require-jsdoc.md
- src/exportParser.js
- test/rules/assertions/requireJsdoc.js
> fix(`require-jsdoc`): do not report `MethodDefinition` with non-public `accessibility`

- .README/rules/match-description.md
- docs/rules/match-description.md
- src/rules/matchDescription.js
> fix(`match-description`): drop `throws` and `yields` from being reported for non-empty descriptions by `nonemptyTags` default

- .README/README.md
- README.md
- src/index.js
> feat: support Flat ESLint config

- src/jsdocUtils.js
- src/rules/matchDescription.js
> fix: revert use of too-high language feature; fixes #1148

- .README/rules/informative-docs.md
- docs/rules/informative-docs.md
- docs/rules/require-jsdoc.md
- src/rules/informativeDocs.js
- test/rules/assertions/informativeDocs.js
- test/rules/assertions/requireJsdoc.js
feat(`informative-docs`): add `excludedTags`; fixes #1153
Also:
- fix(`informative-docs`): proper `aliases` schema
- test(`informative-docs`): check `uselessWords`
- test(`require-jsdoc`): example for Vue components
> feat(`informative-docs`): add `excludedTags`

- .README/rules/require-returns.md
- docs/rules/require-returns.md
- src/iterateJsdoc.js
- src/rules/requireJsdoc.js
- src/rules/requireReturns.js
- test/rules/assertions/requireReturns.js
feat(`require-returns`): add `publicOnly` option; fixes #1137
> feat(`require-returns`): add `publicOnly` option

- docs/rules/require-description-complete-sentence.md
- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
fix(`require-description-complete-sentence`): allow all inline tags at beginning of sentence; fixes #1150
> fix(`require-description-complete-sentence`): allow all inline tags at beginning of sentence

- src/iterateJsdoc.js
- src/rules/requireJsdoc.js
- src/rules/requireReturns.js
fix: fall back to deprecated `getSourceCode()`; fixes #1159
> fix: fall back to deprecated `getSourceCode()`

- docs/rules/require-jsdoc.md
- docs/rules/require-param.md
- src/rules/requireParam.js
- test/rules/assertions/requireParam.js
fix(`require-param`): skip `this` parameter in checks (when followed by destructured content); fixes #1190
> fix(`require-param`): skip `this` parameter in checks (when followed by destructured content)

- docs/rules/require-description-complete-sentence.md
- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
fix(`require-description-complete-sentence`): capture multiple newlines as "paragraphs"; fixes #1193
> fix(`require-description-complete-sentence`): capture multiple newlines as "paragraphs"

- .README/README.md
- .README/rules/informative-docs.md
- README.md
- docs/rules/informative-docs.md
"Restart" doesn't make sense here, I'm pretty sure ["restate"](https://www.merriam-webster.com/dictionary/restate) fits the intended meaning better.
> fix(informative-docs): Improve wording in rule description

- .README/rules/check-line-alignment.md
- docs/rules/check-line-alignment.md
- src/alignTransform.js
- src/rules/checkLineAlignment.js
- test/rules/assertions/checkLineAlignment.js
Makes it possible to change the behavior of `check-line-alignment` so it works as it did before the breaking change introduced in #964.
> feat: add `disableWrapIndent` option to `check-line-alignment` rule

- .README/rules/check-param-names.md
- docs/rules/check-param-names.md
- src/rules/checkParamNames.js
- test/rules/assertions/checkParamNames.js
- test/rules/assertions/requireParam.js
- feat(check-param-names): Add disableMissingParamChecks option
- test(require-param): Add missing line numbers in errors<br>
This ~suppressed~ fixes the output like this:
```
Rule, `require-param`, missing line numbers in errors: 21
```
- This PR closes #1169.
- I believe the tests cases should give us confidence in the behaviour when the option is not provided, and when it is set. Did you want test cases for other languageOptions?
- I haven't been able to run `create-docs` locally :thinking:
> feat(check-param-names): Add disableMissingParamChecks option

- docs/rules/check-tag-names.md
- docs/rules/valid-types.md
- src/rules/validTypes.js
- test/rules/assertions/validTypes.js
fix(`valid-types`): whitelist pratt parser keywords; fixes #1221
> fix(`valid-types`): whitelist pratt parser keywords

- docs/rules/valid-types.md
- src/rules/validTypes.js
- test/rules/assertions/validTypes.js
fix(`valid-types`): disable checking of types/names within `import` tags; fixes #1226
> fix(`valid-types`): disable checking of types/names within `import` tags

- src/utils/hasReturnValue.js
https://typescript-eslint.io/troubleshooting/#the-key-property-is-deprecated-on-type-nodes-use-key-instead-warnings
`typeParameters` are deprecated, and should use `typeArguments` instead. Allow fallback to `typeParameters` to maintain backward compatibility.
> Deprecated `typeParameters`

- .ncurc.cjs
- package.json
- pnpm-lock.yaml
- src/rules/importsAsDependencies.js
Removes `is-builtin-module` and uses the built in function provided by node itself (via `node:module`).
As per your `engines`, all node versions you support have this.
> chore: remove is-builtin-module

- src/iterateJsdoc.js
- test/rules/assertions/requireYields.js
> fix(`require-yields`): avoid error when `ExportNamedDeclaration` has no declaration prop

- docs/rules/match-name.md
- docs/rules/require-description-complete-sentence.md
- docs/rules/require-yields.md
- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
fix(`require-description-complete-sentence`): avoid triggering punctuation warning after Markdown headings; fixes #1220
> fix(`require-description-complete-sentence`): avoid triggering punctuation warning after Markdown headings

- src/rules/requireDescriptionCompleteSentence.js
fix(`require-description-complete-sentence`): regression with heading exempting; fixes #1220
> fix(`require-description-complete-sentence`): regression with heading exempting

- src/index.js
See https://eslint.org/docs/latest/use/configure/configuration-files#configuration-naming-conventions and eg https://github.com/eslint-community/eslint-plugin-eslint-plugin/pull/459
Improves presentation in the config inspector: https://github.com/eslint/config-inspector
> fix: add names to flat configs

- src/index.js
fix: avoid inserting `name` for eslintrc configs; fixes #1239
> fix: avoid inserting `name` for eslintrc configs

- docs/rules/no-undefined-types.md
- src/rules/noUndefinedTypes.js
- src/tagNames.js
- test/rules/assertions/noUndefinedTypes.js
fix(`no-undefined-types`): prevent linting of "type" within @import; fixes #1242
> fix(`no-undefined-types`): prevent linting of "type" within @import

- docs/rules/no-undefined-types.md
- package.json
- pnpm-lock.yaml
- src/rules/noUndefinedTypes.js
- test/rules/assertions/noUndefinedTypes.js
fix(`no-undefined-types`): treat variables imported by `@import` tags as defined; fixes #1244
> fix(`no-undefined-types`): treat variables imported by `@import` tags as defined

- docs/rules/no-undefined-types.md
- package.json
- pnpm-lock.yaml
- src/rules/noUndefinedTypes.js
- test/rules/assertions/noUndefinedTypes.js
fix: Revert "fix(`no-undefined-types`): treat variables imported by `@import` tags as defined"; fixes #1246
This reverts commit 34ba2e01d8de1c8a8558cc3f6f93c23d6bc49250.
Dependency needs CJS build
> fix: Revert "fix(`no-undefined-types`): treat variables imported by `@import` tags as defined"

- docs/rules/check-param-names.md
- src/rules/checkParamNames.js
- test/rules/assertions/checkParamNames.js
feat(`check-param-names`): check `TSMethodSignature` (as on interface methods); fixes #1249
> feat(`check-param-names`): check `TSMethodSignature` (as on interface methods)

- .github/workflows/feature.yaml
- .github/workflows/main.yaml
- src/jsdocUtils.js
- src/rules/checkParamNames.js
- test/rules/assertions/checkParamNames.js
fix(`check-param-names`): proper error messages for rest elements; fixes #1225
> fix(`check-param-names`): proper error messages for rest elements

- docs/rules/check-param-names.md
- docs/rules/require-param.md
- src/rules/requireParam.js
- test/rules/assertions/requireParam.js
fix(`require-param`): proper errors/fixing for succeeding destructured objects; fixes #762
> fix(`require-param`): proper errors/fixing for succeeding destructured objects

- .README/rules/check-template-names.md
- docs/rules/check-template-names.md
- src/index.js
- src/rules/checkTemplateNames.js
- test/rules/assertions/checkTemplateNames.js
- test/rules/ruleNames.json
feat(`check-template-names`): add rule; fixes #1120
> feat(`check-template-names`): add rule

- .README/README.md
- README.md
docs: add `check-template-names` to README; fixes #1263
> docs: add `check-template-names` to README

- docs/rules/check-template-names.md
- docs/rules/require-template.md
- src/rules/checkTemplateNames.js
- src/rules/requireTemplate.js
- test/rules/assertions/checkTemplateNames.js
- test/rules/assertions/requireTemplate.js
fix(`require-template`, `check-template-names`): avoid erring out with missing or bad typedef type; partial fix for #1269
> fix(`require-template`, `check-template-names`): avoid erring out with missing or bad typedef type

- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/convertToJsdocComments.js
- src/rules/requireJsdoc.js
- test/jsdocUtils.js
refactor: make exports named and move utils to own file for reuse
> refactor: make exports named and move utils to own file for reuse

- .README/README.md
- .README/processors.md
- .README/rules/check-examples.md
- README.md
- docs/processors.md
- docs/rules/check-examples.md
- eslint.config.js
- package.json
- pnpm-lock.yaml
- src/bin/generateDocs.js
- src/getJsdocProcessorPlugin.js
- src/index.js
- src/jsdocUtils.js
- test/getJsdocProcessPlugin.js
- test/jsdocUtils.js
feat: add `check-examples` replacement processor; fixes #928
This could really use some real-life testing.
I'm not sure why it shows on the command line, but sometimes doesn't show in VSCode.
> feat: add `check-examples` replacement processor

- src/getJsdocProcessorPlugin.js
> fix(`getJsdocProcessorPlugin`): ensure package.json file is consistently located

- .README/rules/check-template-names.md
- .README/rules/require-template.md
- docs/rules/check-template-names.md
- docs/rules/require-template.md
- src/rules/checkTemplateNames.js
- src/rules/requireTemplate.js
- test/rules/assertions/checkTemplateNames.js
- test/rules/assertions/requireTemplate.js
feat(`require-template`, `check-template-names`): add support `ClassDeclaration`, `FunctionDeclaration`, `TSInterfaceDeclaration`
> feat(`require-template`, `check-template-names`): add support for more template checks

- docs/rules/check-template-names.md
Syntax highlighting of code blocks in the [`check-template-names`](https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/check-template-names.md) rule is bad because `js` is defined, but the code is TypeScript.
> docs: use `ts` for TypeScript code blocks

- .README/README.md
- .README/rules/lines-before-block.md
- README.md
- docs/rules/lines-before-block.md
- src/index.js
- src/rules/linesBeforeBlock.js
- test/rules/assertions/linesBeforeBlock.js
- test/rules/ruleNames.json
feat(`lines-before-block`): add new rule; fixes #1209
Adds new rule to recommended
> feat(`lines-before-block`): add new rule

- src/index.js
fix(`lines-before-block`): remove rule from recommended
Have to selectively enable the `lines-before-block` rule to have it apply now.
The rule still has some issues to work out, so dropping from recommended for now.
> fix(`lines-before-block`): remove rule from recommended

- .README/README.md
- README.md
- src/index.js
Fixes #1175.
https://github.com/gajus/eslint-plugin-jsdoc/issues/1175#issuecomment-2272660984 was really helpful for tinkering with the rule names. I ended up splitting them into three sections:
* **Logical**: rules that enforce proper tag values
* **Requirements**: rules that enforce tags exist
* **Stylistic**: rules that enforce tag formatting and styles
Edit: per the review, there's now also:
* **Contents**: rules that check names and descriptions
In theory these could also be made for non-TypeScript and/or eslintrc, but ... I don't use those and am not as familiar with them. So I held off.
> feat: added granular flat TypeScript configs

- src/index.js
Fixes #1307.
This was a silly mistake I made in the PR, sorry.
> fix: properly include options in ruleset factories

- .README/rules/no-bad-blocks.md
- .README/rules/text-escaping.md
- .README/settings.md
- docs/rules/check-param-names.md
- docs/rules/no-bad-blocks.md
- docs/rules/require-param.md
- docs/rules/text-escaping.md
- docs/settings.md
- src/rules/checkParamNames.js
- test/rules/assertions/checkParamNames.js
- test/rules/assertions/requireParam.js
fix(`check-param-names`): check against whitelist of acceptable function nodes so that non-function global contexts do not err; fixes #1303
Also adds warning in docs for use of global settings contexts.
> fix(`check-param-names`): check against whitelist of acceptable function nodes so that non-function global contexts do not err

- docs/rules/require-returns-check.md
- src/utils/hasReturnValue.js
- test/rules/assertions/requireReturnsCheck.js
fix(`require-returns-check`): allow infinite for loops to have only one branch to return; fixes #1315
> fix(`require-returns-check`): allow infinite for loops to have only one branch to return

- docs/rules/require-jsdoc.md
- src/exportParser.js
- test/rules/assertions/requireJsdoc.js
fix(`require-jsdoc`): allow `TSTypeAliasDeclaration` to be detected for export; fixes #1319
> fix(`require-jsdoc`): allow `TSTypeAliasDeclaration` to be detected for export

- .README/rules/require-param.md
- docs/rules/require-param.md
- src/rules/requireParam.js
- test/rules/assertions/requireParam.js
feat(`require-param`): add `ignoreWhenAllParamsMissing` option; fixes #1317
> feat(`require-param`): add `ignoreWhenAllParamsMissing` option

- docs/rules/check-alignment.md
- src/iterateJsdoc.js
- test/rules/assertions/checkAlignment.js
fix(`check-alignment`): handle zero indent; fixes #1322
> fix(`check-alignment`): handle zero indent

- docs/rules/require-hyphen-before-param-description.md
- src/rules/requireHyphenBeforeParamDescription.js
- test/rules/assertions/requireHyphenBeforeParamDescription.js
fix(`require-hyphen-before-param-description`): inject hyphen at proper place with multiline type
> fix(`require-hyphen-before-param-description`): inject hyphen at proper place with multiline type

- docs/rules/match-name.md
- package.json
- pnpm-lock.yaml
- test/rules/assertions/matchName.js
- test/rules/assertions/requireHyphenBeforeParamDescription.js
feat(`require-hyphen-before-param-description`): ensure template will be properly stringified; fixes #1326
Note that `match-name` will now have to take into account any optional brackets and default in `allowName`
> feat(`require-hyphen-before-param-description`): ensure template will be properly stringified

- docs/rules/match-name.md
- src/rules/matchName.js
- test/rules/assertions/matchName.js
fix(`match-name`): revert to prior correct behavior of ignoring optional and default code surrounding name
> fix(`match-name`): revert to prior correct behavior of ignoring optional and default code surrounding name

- src/rules/noMultiAsterisks.js
This PR add the missing `meta.docs.description` for rule `no-multi-asterisks`.
> fix(no-multi-asterisks): add missing `docs.description`

- src/rules/textEscaping.js
This PR add the missing `meta.docs.description` for rule `text-escaping`.
> fix(text-escaping): add missing `docs.description`

- docs/rules/check-access.md
- docs/rules/lines-before-block.md
- docs/rules/no-defaults.md
- docs/rules/require-asterisk-prefix.md
- docs/rules/require-template.md
- docs/rules/require-throws.md
Currently the following rules have different recommended status than their respective status in the `README.md` recommended list: 
- `check-access`
- `lines-before-block`
- `no-defaults`
- `require-asterisk-prefix`
- `require-template`
- `require-throws`
This PR fixes that
> docs: make rule docs reflect their recommended status correctly

- package.json
Since v48.0.0, `iterateJsdoc` cannot be imported anymore. This PR adds `iterateJsdoc` to the `exports` field of the package, in order for external libraries to use it (we use it to build custom JSDoc rules).
Thanks!
> Ability to import iterateJsdoc

- .README/rules/lines-before-block.md
- docs/rules/lines-before-block.md
- src/rules/linesBeforeBlock.js
- test/rules/assertions/linesBeforeBlock.js
Fixes #1296.
Intentionally phrased as a `fix` rather than a `feat` because IMO reporting on JSDoc blocks at the beginning of a block by default is a bug. But this does add a _feature_ by way of the new option... 🤷
I don't love the name `checkBlockStarts`. But I couldn't think of anything better.
Doesn't handle _array_ starts (`[\n/** ... */]`) because that wasn't requested in any issue. I suppose that could be another option? I propose leaving that as a followup.
> fix(lines-before-block): move start-of-block checking behind off-by-default checkBlockStarts option

- src/index.js
Not all config keys were included in the Record, only the recommended ones.
> fix: update configs types

- src/rules/checkTemplateNames.js
fix(`check-template-names`): stop restricting template names to single letters; fixes #1352
Single letters in JSDoc blocks still expected for template names in `require-template` rule.
> fix(`check-template-names`): stop restricting template names to single letters

- .github/workflows/feature.yaml
- .github/workflows/main.yaml
This PR bumps GitHub Actions to their latest major versions. Main change is they are now using Node 20 instead of 16, which was EOL as of April 2022:
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `actions/setup-node` can be [found here](https://github.com/actions/setup-node/releases)
> ci: update github actions

- .README/rules/text-escaping.md
- docs/rules/text-escaping.md
- src/rules/textEscaping.js
- test/rules/assertions/textEscaping.js
fix(`text-escaping`): always allow content in example tags; fixes #1360
> fix(`text-escaping`): always allow content in example tags

- docs/rules/empty-tags.md
- src/rules/emptyTags.js
- test/rules/assertions/emptyTags.js
fix(`empty-tags`): allow for JSDoc-block final asterisks; fixes #670
> fix(`empty-tags`): allow for JSDoc-block final asterisks

- docs/rules/no-undefined-types.md
- src/rules/noUndefinedTypes.js
- test/rules/assertions/noUndefinedTypes.js
Fixes https://github.com/gajus/eslint-plugin-jsdoc/issues/178 and https://github.com/gajus/eslint-plugin-jsdoc/issues/1342
> fix(no-undefined-types): allow any available identifier; fixes #178,#1342

- src/index.js
The "requirements" group of configurations is missing from the type definition.
> Add missing config type(s)

- src/rules/noUndefinedTypes.js
fix(`no-undefined-types`): workaround `parse-imports-exports` bug in handling trailing whitespace; fixes #1373
> fix(`no-undefined-types`): workaround `parse-imports-exports` bug in handling trailing whitespace

- docs/rules/lines-before-block.md
- src/rules/linesBeforeBlock.js
- test/rules/assertions/linesBeforeBlock.js
Fixes #1379 and #1343.
I initially went for a targeted fix that would only solve my issue, #1379, but I noticed that all punctuators didn't seem to me like reasonable places to insert a line before. As I had also been facing #1343 solving it was nice too.
Of course what "feels" right is obviously subjective so let me know if you want me to put this behind an option. I considered exposing `lintedPunctuators` as an option but it felt too granular. Disabling `&` could be useful to users of Prettier that want to set `ignoreSameLine` to `false` though. Specifically, Prettier really isn't fond of the formatting in this snippet:
```js
type IntersectionDocumentation =
& { someProp: number }
/** Description. */
& { otherProp: string };
```
And will format it like so:
```js
type …
```
> fix(`lines-before-block`): Only trigger after ';', '}', '|', and '&'

- docs/rules/lines-before-block.md
- src/rules/linesBeforeBlock.js
- test/rules/assertions/linesBeforeBlock.js
A follow up to #1383. Sorry for another PR in quick succession along the same lines. However I was thinking about the solution and I wasn't happy with having to maintain a list of punctuators that are checked. Specifically I began to feel like the default should be checking. I also added some more tests to cover some interesting cases I thought of.
> fix(`lines-before-block`): Switch to a whitelist of punctuators

- src/rules/noUndefinedTypes.js
> fix(`no-undefined-types`): avoid eslint 8 error

- docs/rules/valid-types.md
- src/rules/validTypes.js
- test/rules/assertions/validTypes.js
Fixed #1381.
I looked at a handful of ways to do this:
- Hook into `@es-joy/jsdoccoment`'s `parseComment` function. Specifically I was hoping to wrap the type parsing logic. This seemed like the most elegant option but it fell flat. While this is technically possible I would have to hardcode that `getTransformer` returns the type parser at index `1` in order to wrap it and make it aware of this edge case.
- Rerun the parser with `noTypes` set to include the tag. While possible it'd mean rerunning parsing from scratch. I'm okay with switching to this approach if you'd like.
- What I actually did, which is to move `tag.type` to `tag.description` if it looks like a JSDoc tag. The type parser expects the type to be formatted as exactly `{type}` and whitespace is preserved so the conversion …
>  fix(`valid-types`): fix parsing of expressions like `@returns {@link SomeType}`

- docs/rules/require-param.md
- package.json
- pnpm-lock.yaml
- test/rules/assertions/requireParam.js
fix(`require-param`): update jsdoccomment to support exported TSFunctionType type; fixes #1386
> fix(`require-param`): update jsdoccomment to support exported TSFunctionType type

- src/getJsdocProcessorPlugin.js
- test/getJsdocProcessPlugin.js
feat(getJsdocProcessorPlugin): allow `exampleCodeRegex` and `rejectExampleCodeRegex` to be RegExp objects
Also:
- fix(getJsdocProcessorPlugin): avoid auto-fix being triggered for example text while we still have no fixers applied
> feat(getJsdocProcessorPlugin): allow `exampleCodeRegex` and `rejectExampleCodeRegex` to be RegExp objects

- .github/workflows/feature.yaml
- package.json
Fixes #1398
This reverts commit f85ffc6186162c8a600ecf9106565461884146a9. to allow Node v20.11.0+
> fix: revert "fix: require node v22"

- docs/rules/no-undefined-types.md
- src/rules/noUndefinedTypes.js
- test/rules/assertions/noUndefinedTypes.js
fix(`no-undefined-types`): mark sister method and property names as defined; fixes #1403 ; fixes #1119
> fix(`no-undefined-types`): mark sister method and property names as defined

- .README/rules/lines-before-block.md
- docs/rules/lines-before-block.md
- src/rules/linesBeforeBlock.js
- test/rules/assertions/linesBeforeBlock.js
feat(`lines-before-block`): add default-on `ignoreSingleLines` option; fixes #1295
> feat(`lines-before-block`): add default-on `ignoreSingleLines` option

- docs/rules/no-undefined-types.md
- src/rules/noUndefinedTypes.js
- test/rules/assertions/noUndefinedTypes.js
fix(`no-undefined-types`): liberalize checks to reallow for unknown properties on imports and defined globals; fixes #1412
> fix(`no-undefined-types`): liberalize checks to reallow for unknown properties on imports and defined globals

- docs/rules/no-undefined-types.md
- src/rules/noUndefinedTypes.js
- test/rules/assertions/noUndefinedTypes.js
fix(`no-undefined-types`): exempt import tags from property checks; fixes #1416
> fix(`no-undefined-types`): exempt import tags from property checks

- docs/rules/require-template.md
- src/jsdocUtils.js
- src/rules/requireTemplate.js
- test/rules/assertions/requireTemplate.js
fix(`require-template`, `no-undefined-types`, `valid-types`): properly parse template tags with defaults; fixes #1418
> fix(`require-template`, `no-undefined-types`, `valid-types`): properly parse template tags with defaults

- .README/rules/multiline-blocks.md
- docs/rules/multiline-blocks.md
- src/rules/multilineBlocks.js
- test/rules/assertions/multilineBlocks.js
feat(`multiline-blocks`): adds `requireSingleLineUnderCount` option; fixes #1158
> feat(`multiline-blocks`): adds `requireSingleLineUnderCount` option

- docs/rules/no-undefined-types.md
- src/rules/noUndefinedTypes.js
- test/rules/assertions/noUndefinedTypes.js
fix(`no-undefined-types`): Add `Intl` to global types and ensure arbitrary properties of globals can be addressed; fixes #1423
> fix(`no-undefined-types`): Add `Intl` to global types and ensure arbitrary properties of globals can be addressed

- src/rules/matchName.js
- src/rules/requireAsteriskPrefix.js
- src/rules/sortTags.js
Some rules, for example [match-name](https://github.com/gajus/eslint-plugin-jsdoc/blob/1f015ca70a13d055b4ebd2b8638b4be35abc05ba/src/rules/matchName.js#L112) currently allow extra properties to be passed in options object, which should not be allowed. This makes it easier for typos in rule options to go unnoticed.
This PR simply disallows extra properties in rules' schemas which currently allow them.
> fix: disallow extra properties in rule options

- .husky/post-checkout
- .husky/post-commit
- .husky/post-merge
- .husky/post-rewrite
- .husky/pre-commit
- .husky/pre-push
- CONTRIBUTING.md
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/bin/generateDocs.js
- src/bin/generateRule.js
- test/rules/index.js
I started investigating #1432, but quickly hit Windows incompatibilities.
---
This fixes `pnpm build` on Windows.
Otherwise, the string escapes in the `build` script are misinterpreted.
After enabling `shellEmulator`, husky needed to be moved off npm. I can't repro the issues noted with pnpm over npm in CONTRIBUTING.
---
Also, gitdown doesn't work on Windows, [this glob](https://github.com/gajus/gitdown/blob/a323123bc1d8c8bb9f8c516406aefe5ddca80ff4/src/parser.js#L190) evals to windows backslashes when `glob` wants forward slashes; I have to use `git push --no-verify`.
> chore: enable pnpm shellEmulator

- src/rules/validTypes.js
fix(`valid-types`): allow `extends` for namepath; fixes #1455
> fix(`valid-types`): allow `extends` for namepath

- .README/README.md
- README.md
Small not-important touchup: I noticed a few rules weren't quite in the same order as the table later in the file. This alphabetizes them to be consistent.
> docs: correct alphabetization of rules in example config block

- docs/rules/valid-types.md
- src/rules/validTypes.js
- test/rules/assertions/validTypes.js
fix(`valid-types`): try parsing whole item before splitting into commas; fixes #1464
> fix(`valid-types`): try parsing whole item before splitting into commas

- .README/rules/require-hyphen-before-param-description.md
- docs/rules/require-hyphen-before-param-description.md
- src/rules/requireHyphenBeforeParamDescription.js
- test/rules/assertions/requireHyphenBeforeParamDescription.js
feat(`require-hyphen-before-param-description`): when `always` is set, disallow hyphen at end of line; fixes #1435
> feat(`require-hyphen-before-param-description`): when `always` is set, disallow hyphen at end of line

- docs/rules/check-template-names.md
- src/rules/checkTemplateNames.js
- src/rules/requireTemplate.js
- test/rules/assertions/checkTemplateNames.js
fix(`check-template-names`, `require-template`): ensure template name  is based on what is within any brackets and preceding equal sign; fixes #1466
> fix(`check-template-names`, `require-template`): ensure template name  is based on what is within any brackets and preceding equal sign

- src/getJsdocProcessorPlugin.js
fix(`getJsdocProcessorPlugin`): reenable fixes (but disabling fixers for @example issues); fixes #1431
> fix(`getJsdocProcessorPlugin`): reenable fixes (but disabling fixers for @example issues)

- .README/advanced.md
- docs/advanced.md
- src/index-cjs.js
- src/index.js
fix(`extraRuleDefinitions.forbid` jsdoc function option): point default link to advanced page
Also:
- docs: document `url` and fix `description` property
> fix(`extraRuleDefinitions.forbid` jsdoc function option): point default link to advanced page

- .README/processors.md
- .README/rules/check-examples.md
- docs/processors.md
- docs/rules/check-examples.md
- src/index-cjs.js
- src/index.js
- src/rules/checkExamples.js
fix(`examples` configs): disable `@typescript-eslint/no-unsed-vars`
Also:
- docs(processor): more on typescript usage
> fix(`examples` configs): disable `@typescript-eslint/no-unsed-vars`

- .README/rules/require-param.md
- docs/rules/require-param.md
- src/rules.d.ts
- src/rules/requireParam.js
- test/rules/assertions/requireParam.js
feat(`require-param`): add `interfaceExemptsParamsCheck` option; fixes #1511
> feat(`require-param`): add `interfaceExemptsParamsCheck` option

- .README/rules/require-tags.md
- README.md
- docs/rules/require-tags.md
- src/index-cjs.js
- src/index.js
- src/rules.d.ts
- src/rules/requireTags.js
- test/rules/assertions/requireTags.js
- test/rules/ruleNames.json
fix(`require-tags`): change rule name to be consistent with other rules
Changes `required-tags` to `require-tags`.
> fix(`require-tags`): change rule name to be consistent with other rules

- .README/rules/no-undefined-types.md
- docs/rules/no-undefined-types.md
- src/iterateJsdoc.js
- src/rules.d.ts
- src/rules/noUndefinedTypes.js
- test/rules/assertions/noUndefinedTypes.js
feat(`no-undefined-types`): `checkUsedTypedefs` option; fixes #1165
> feat(`no-undefined-types`): `checkUsedTypedefs` option

- docs/rules/prefer-import-tag.md
- package.json
- pnpm-lock.yaml
- src/index-cjs.js
- src/index.js
- src/iterateJsdoc.js
- src/rules/preferImportTag.js
- test/rules/assertions/noRestrictedSyntax.js
- test/rules/assertions/preferImportTag.js
feat: add `flat/recommended-mixed` config; fixes #1101
> feat: add `flat/recommended-mixed` config

- docs/rules/require-param.md
- package.json
- pnpm-lock.yaml
- src/rules/requireParam.js
- test/rules/assertions/requireParam.js
Update the return type of the `findExpectedIndex` function to include `foundIndex` and `tagLineCount`. Adjust the logic in the calling function to utilize the new return structure, ensuring proper handling of expected indices and offsets.
Fixes #1530
> fix(requireParam): update return type to include foundIndex and tagLineCount

- docs/rules/valid-types.md
- package.json
- pnpm-lock.yaml
- src/bin/generateOptions.js
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/validTypes.js
- test/rules/assertions/validTypes.js
fix: parse distinctly for names vs. namepaths
Also:
- chore: update jsdocccomment and jsdoc-type-pratt-parser
> fix: parse distinctly for names vs. namepaths
