gajus/eslint-plugin-jsdoc

- .babelrc
- .travis.yml
- package.json
Also, don't test node@5, it's EOL
https://github.com/gajus/eslint-plugin-jsdoc/commit/8c9f89e5317f376a4f19c9c507ac10481d8c061c#commitcomment-21764339
> fix: set node@4 as minimum

- src/rules/noUndefinedTypes.js
- test/rules/assertions/noUndefinedTypes.js
> fix: 'Object' and 'Array' are undefined in sourceType: module

- src/rules/requireExample.js
- src/rules/requireParam.js
- test/rules/assertions/requireExample.js
- test/rules/assertions/requireParam.js
Reverts gajus/eslint-plugin-jsdoc#86
> fix: revert @ private skip require checks (issue #78)

- src/rules/newlineAfterDescription.js
- Fix failing test by adding missing space (as added by rule along with newline)
> Test expecting space

- package.json
Upgrading comment-parser dependency to 0.5.1 fixes issue #122
> Fixes issue #122

- .README/rules/check-examples.md
- README.md
- src/bin/readme-assertions.js
- test/rules/assertions/checkExamples.js
> fix: checkExample code with backticks, error messages, assertion link

- .README/README.md
- .README/rules/check-alignment.md
- README.md
- src/index.js
- src/rules/checkAlignment.js
- test/rules/assertions/checkAlignment.js
- test/rules/index.js
Reports against second example here: https://github.com/gajus/eslint-plugin-jsdoc/issues/76
> feat: add rule check alignment

- README.md
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/requireReturns.js
- test/rules/assertions/requireReturns.js
Suppress require-returns for @override, @constructor, and class constructor
Fixes part of #107.
Have a couple more on top of this (including a fix for #142 and more toward #107) which I can submit if this one is all right.
> Require returns

- .README/rules/valid-types.md
Sorry, should have gotten this into the last PR...
> - Document new `valid-types` behavior

- src/rules/requireHyphenBeforeParamDescription.js
> fix: remove regexp unsupported by node 6

- src/index.js
- src/rules/matchDescription.js
- test/rules/assertions/matchDescription.js
- test/rules/index.js
Fixes part of #107.
This is working in my local Node environment, but not with Node 4 which doesn't support Unicode regexes. Can we bump to Node >= 6?
> - Add matchDescription for #107

- README.md
- src/rules/checkParamNames.js
- test/rules/assertions/checkParamNames.js
- Report duplicate param names as such
(Behavior noticed missing in comparing with `valid-jsdoc`; #107)
Btw, I'm happy to merge these PRs of mine or others I'm comfortable merging, @gajus , but just would like to know if you have any specific preferred procedures for when I might directly merge and when to submit PRs (or submit a PR and merge it myself)...
> Duplicate params

- src/rules/requireJsdoc.js
- test/rules/assertions/requireJsdoc.js
> require-jsdoc exempt empty functions option (fix for #77)

- src/eslint/getJSDocComment.js
> refactor: avoid importing eslint internal util

- src/rules/checkAlignment.js
- test/rules/assertions/checkAlignment.js
* add fixer for rule `check-alignment`.
> enhancement(check-alignment): add fixer

- README.md
- package.json
- src/jsdocUtils.js
- test/rules/assertions/checkParamNames.js
- test/rules/assertions/requireParam.js
Fixes #177 
Closes #179 
This is the fix from #179 without the infrastructure changes.
> Support TypeScript parameter properties

- .travis.yml
- package.json
- src/bin/generateReadme.js
closes #238 .
There is one problem. Gitdown will throw error if the current branch is not master. Can you help with this @gajus?
```
Error: Branch ("my-my-branch") definition does not exist in the config.
at Object.gitinfo.getRemoteUrl (node_modules/gitinfo/dist/gitinfo.js:816:13)
at Object.gitinfo.getUsername (node_modules/gitinfo/dist/gitinfo.js:868:59)
```
> build: make create-readme part of test

- README.md
- test/rules/assertions/checkIndentation.js
As requested by @brettz9:
https://github.com/gajus/eslint-plugin-jsdoc/pull/388#discussion_r330857100
> Additional assertions for `check-indentation`

- README.md
- src/jsdocUtils.js
- test/rules/assertions/checkParamNames.js
> fix: handle ts constructor as arg

- README.md
- test/rules/assertions/requireDescription.js
Write tests to demonstrate expected behaviors. Invalid one should pass.
Goes with https://github.com/gajus/eslint-plugin-jsdoc/issues/582
> Require description on TS Property Signature

- .README/README.md
- README.md
Link to chat server set up per #601.
> Add link to Discord chat.

- .README/rules/check-types.md
- README.md
There was an improper sentence that needed decoded. The use of a bulleted-list also helped with the understanding of what the author was intending to say.
> Update docs for typo and readability

- README.md
- src/getDefaultTagStructureForMode.js
- src/rules/validTypes.js
- test/rules/assertions/validTypes.js
feat(`valid-types`): require whitelist of types and prevent names with `suppress` tag
> feat(`valid-types`): require whitelist of types and prevent names with `suppress` tag

- src/rules/requireJsdoc.js
Fixes #843 for me. Let me know if I need to do anything else to get this merged.
> fix(require-jsdoc): add column to end line

- .README/rules/require-returns-check.md
- README.md
- src/iterateJsdoc.js
- src/rules/requireReturnsCheck.js
- src/utils/hasReturnValue.js
- test/rules/assertions/requireReturnsCheck.js
fix(`require-returns-check`); checks that all branches of final node return; fixes #892
> Check that all branches of final node return

- .README/README.md
- README.md
Adding per https://github.com/gajus/eslint-plugin-jsdoc/issues/693#issuecomment-1403529214
> docs: add missing `sort-tags` rule from listing

- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
> fix: avoid erring with blank lines

- README.md
- src/utils/hasReturnValue.js
- test/rules/assertions/requireReturnsCheck.js
> fix(`require-returns-check`): allow infinite loops to only have one branch return

- README.md
- src/rules/requireDescriptionCompleteSentence.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
> fix(`require-description-complete-sentence`): report bare punctuation

- .README/rules/valid-types.md
- README.md
> docs(`valid-types`): update namepath-accepting listing

- .README/rules/check-line-alignment.md
- README.md
> docs: fix `postHyphens` -> `postHyphen`

- .README/rules/check-line-alignment.md
- README.md
- src/alignTransform.js
- src/rules/checkLineAlignment.js
- test/rules/assertions/checkLineAlignment.js
fixes #715
Also adds missing docs for `preserveMainDescriptionPostDelimiter`.
> feat: `wrapIndent` option

- package-lock.json
- src/bin/generateReadme.js
- src/iterateJsdoc.js
- test/rules/assertions/flatConfig.js
- test/rules/index.js
#989
Also:
- chore: update lock file
> fix: avoid erring out with flat config

- src/iterateJsdoc.js
> fix: support detection of typescript parser for flat config

- src/bin/generateRule.js
- src/index.js
> chore: fix generateRule

- README.md
- src/bin/generateRule.js
- src/rules/matchName.js
- src/rules/multilineBlocks.js
- src/rules/noMultiAsterisks.js
- src/rules/sortTags.js
- src/rules/tagLines.js
- src/rules/textEscaping.js
- src/rules/validTypes.js
- test/rules/assertions/multilineBlocks.js
- test/rules/assertions/validTypes.js
- fix: sp. to prevent `additionalProperties`
- fix: remove/change unused properties
Also:
- chore: specify sample line number when creating sample error for rule
> Additional properties

- README.md
- src/rules/requireReturns.js
- test/rules/assertions/requireReturns.js
> fix(`require-returns`): regression with forcing all async returns to be ignored

- package-lock.json
- package.json
> fix: bump engines

- README.md
- src/iterateJsdoc.js
- test/rules/assertions/requireDescriptionCompleteSentence.js
- test/rules/assertions/tagLines.js
> fix: description retrieval logic was problematic for single line tags

- .README/rules/check-tag-names.md
- README.md
> docs(`check-tag-names`): add docs on rejecting tags

- .README/README.md
- .README/rules/no-blank-blocks.md
- README.md
- src/index.js
- src/rules/noBlankBlocks.js
- test/rules/assertions/noBlankBlocks.js
- test/rules/ruleNames.json
> feat(`no-blank-blocks`): add new rule

- docs/rules/no-restricted-syntax.md
- package.json
- pnpm-lock.yaml
- test/iterateJsdoc.js
- test/rules/assertions/noRestrictedSyntax.js
Also:
- test: demo use of `inlineTags`
> feat: update @es-joy/jsdoccomment

- docs/rules/no-undefined-types.md
- src/getDefaultTagStructureForMode.js
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/checkLineAlignment.js
- src/rules/checkTypes.js
- src/rules/emptyTags.js
- src/rules/matchDescription.js
- src/rules/noBadBlocks.js
- src/rules/requireDescriptionCompleteSentence.js
- src/rules/requireJsdoc.js
- test/rules/assertions/noUndefinedTypes.js
- fix(`no-undefined-types`): add line info to inline tags; fixes #1079
Also:
- fix: allow `ArrayPattern` with empty value
- refactor: ts work
> fix(`no-undefined-types`): add line info to inline tags

- docs/rules/require-description-complete-sentence.md
- docs/rules/require-description.md
- docs/rules/require-jsdoc.md
- docs/rules/require-param-description.md
- docs/rules/require-param-name.md
- docs/rules/require-param-type.md
- docs/rules/require-param.md
- docs/rules/require-property-description.md
- docs/rules/require-property-name.md
- docs/rules/require-property-type.md
- docs/rules/require-property.md
- docs/rules/require-returns-check.md
- docs/rules/require-returns-description.md
- docs/rules/require-returns-type.md
- docs/rules/require-returns.md
- docs/rules/require-yields-check.md
- docs/rules/require-yields.md
- src/bin/generateDocs.js
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/checkParamNames.js
- src/rules/noUndefinedTypes.js
- src/rules/requireJsdoc.js
- src/rules/sortTags.js
- src/utils/hasReturnValue.js
- test/rules/assertions/requireJsdoc.js
- tsconfig.json
> docs: due to ordering issue, some doc files output under wrong name

- .README/settings.md
- docs/rules/no-undefined-types.md
- docs/settings.md
- src/exportParser.js
- src/iterateJsdoc.js
- src/jsdocUtils.js
- src/rules/requireJsdoc.js
- test/rules/assertions/noUndefinedTypes.js
- docs: reference `namepath-or-url-referencing`
- refactor: TS work
- test: add case for `namepath-or-url-referencing`
> docs: reference `namepath-or-url-referencing`

- .README/README.md
- README.md
- src/index.js
Also:
- docs: adds info on TS recommended rules
> feat(`no-defaults`): make no-defaults on by default

- docs/rules/require-returns.md
- src/iterateJsdoc.js
- src/rules/noMissingSyntax.js
- src/rules/noRestrictedSyntax.js
- src/rules/requireReturns.js
- test/rules/assertions/requireReturns.js
> feat(`require-returns`): per-context `forceRequireReturn`

- src/rules/importsAsDependencies.js
- test/rules/assertions/importsAsDependencies.js
> fix(`imports-as-dependencies`): check for `types` in `package.json` and if not present, check `@types`

- .npmignore
Block docs and declaration files for now...
> chore: ignore declaration files and docs

- .npmignore
feat: expose TS types for index file; fixes #1130
Adds types
> feat: expose TS types for index file

- eslint.config.mjs
- package.json
- src/index.js
> Flat config

- .README/rules/informative-docs.md
- docs/rules/informative-docs.md
> docs: mention excludedTags in informative-docs docs

- .README/rules/check-values.md
- .README/rules/no-undefined-types.md
- .babelrc.json
- docs/rules/check-values.md
- docs/rules/no-undefined-types.md
- package.json
- pnpm-lock.yaml
- src/import-worker.mjs
- src/rules/checkValues.js
- src/rules/noUndefinedTypes.js
- test/rules/assertions/checkValues.js
- test/rules/assertions/noUndefinedTypes.js
- tsconfig.json
- feat(`check-values`): checks for valid `@import` syntax
- fix(`no-undefined-types`): treat variables imported by `@import` tags as defined; fixes #1244
> Checking @import tags

- docs/rules/no-types.md
- src/rules/noTypes.js
- test/rules/assertions/noTypes.js
feat(`no-types`): add `TSMethodSignature`; fixes #1249
> feat(`no-types`): add `TSMethodSignature`

- .README/README.md
- README.md
docs: add new rules to listing
> docs: add new rules to listing

- docs/rules/check-template-names.md
- docs/rules/require-template.md
- src/rules/checkTemplateNames.js
- src/rules/requireTemplate.js
- test/rules/assertions/checkTemplateNames.js
- test/rules/assertions/requireTemplate.js
fix(`require-template`, `check-template-names`): check property tags; fixes #1269
> fix(`require-template`, `check-template-names`): check @property tags

- .README/processors.md
- docs/processors.md
- package.json
- src/index.js
fix: move processor to own file; fixes #1277; fixes #1278
> fix: move processor to own file

- .README/processors.md
- docs/processors.md
- src/index.js
fix(examples processor): ensure config can be loaded with plugins
Also:
- docs: fix processor docs
> fix(examples processor): ensure config can be loaded with plugins

- .README/rules/check-template-names.md
- .README/rules/require-template.md
- docs/rules/check-template-names.md
- docs/rules/require-template.md
- src/rules/checkTemplateNames.js
- src/rules/requireTemplate.js
- test/rules/assertions/checkTemplateNames.js
- test/rules/assertions/requireTemplate.js
- feat(`check-template-names`): check callback/function tag blocks
- feat(`require-template`): check callback/function tag block content
> feat(`check-template-names`, `require-template`): check callback/function tag blocks

- src/rules/checkTemplateNames.js
> docs: fix URL

- .README/rules/check-access.md
- .README/rules/lines-before-block.md
- .README/rules/no-defaults.md
- .README/rules/require-asterisk-prefix.md
- .README/rules/require-template.md
- .README/rules/require-throws.md
- docs/rules/check-access.md
- docs/rules/lines-before-block.md
- docs/rules/no-defaults.md
- docs/rules/require-asterisk-prefix.md
- docs/rules/require-template.md
- docs/rules/require-throws.md
Duplicate of this https://github.com/gajus/eslint-plugin-jsdoc/pull/1335, but this time I updated the correct files
> docs: update rule docs to reflect correctly if they are recommended

- .ncurc.cjs
- package.json
- pnpm-lock.yaml
fix: revert are-docs-informative upgrade; fixes #1393
> fix: revert are-docs-informative upgrade

- .ncurc.cjs
- package.json
- pnpm-lock.yaml
> fix: revert `are-docs-informative` while still using CJS; fixes #1400

- docs/rules/require-jsdoc.md
- src/rules/requireJsdoc.js
- test/rules/assertions/requireJsdoc.js
fix(`require-jsdoc`): check interfaces within file for comment blocks; fixes #768
> fix(`require-jsdoc`): check interfaces within file for comment blocks

- docs/rules/no-undefined-types.md
- src/rules/noUndefinedTypes.js
- test/rules/assertions/noUndefinedTypes.js
fix(`no-undefined-types`): check class and interface globals; fixes #1420
> fix(`no-undefined-types`): check class and interface globals

- docs/rules/check-alignment.md
- src/rules/checkAlignment.js
- test/rules/assertions/checkAlignment.js
feat(check-alignment): add `innerIndent` integer option; fixes #1351
> feat(check-alignment): add `innerIndent` integer option

- .README/rules/tag-lines.md
- README.md
- docs/rules/tag-lines.md
- src/rules.d.ts
- src/rules/tagLines.js
- test/rules/assertions/tagLines.js
feat(`tag-lines`): `maxBlockLines` option; fixes #1346
> feat(`tag-lines`): `maxBlockLines` option
